### ISSUE TITLE
Error:(3, 55) error: package com.google.android.vending.expansion.downloader does not exist

### ISSUE THREAD

**Issue by SebDigital** [agamemnus/cordova-plugin-xapkreader#101]
Hi, I have Cordova Android 6.2.3 and Android Studio 2.3.3 and I have this error when I build Sign APK
Error:(3, 55) error: package com.google.android.vending.expansion.downloader does not exist]

Thans a lot, I am using also the cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0

Thanks!

Seb

**Comment by SebDigital** [comment]
Futher on this one, it looks like it is in the XPAKAlarmReceiver.java:

package com.flyingsoftgames.xapkreader;

import com.google.android.vending.expansion.downloader.DownloaderClientMarshaller;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager.NameNotFoundException;

public class XAPKAlarmReceiver extends BroadcastReceiver {
 @Override public void onReceive (Context context, Intent intent) {
  try {
   DownloaderClientMarshaller.startDownloadServiceIfRequired(context, intent, XAPKDownloaderService.class);
  } catch (NameNotFoundException e) {
   e.printStackTrace();
  }
 }
}

Thanks!

Seb

**Comment by agamemnus** [comment]
https://github.com/agamemnus/cordova-plugin-xapkreader/blob/cordova-6.5.0/android-sdk/extras/google/play_apk_expansion/downloader_library/src/com/google/android/vending/expansion/downloader/IDownloaderClient.java

It exists. Not sure what's going on with your build...

**Comment by SebDigital** [comment]
thanks, I have noticed that in my build.gradle I have this:
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    debugCompile(project(path: "phonegap-facebook-plugin:FacebookLib", configuration: "debug")){
        exclude module:("CordovaLib")
    }
    releaseCompile(project(path: "phonegap-facebook-plugin:FacebookLib", configuration: "release")){
        exclude module:("CordovaLib")
    }
    // SUB-PROJECT DEPENDENCIES END
}

There is nothing about the plugin, should we have some call here? what will it be if yes ? thanks!
Seb

**Comment by SebDigital** [comment]
Same in settings.gradle
// GENERATED FILE - DO NOT EDIT
include ":"
include ":CordovaLib"
include ":phonegap-facebook-plugin:FacebookLib"
project(":phonegap-facebook-plugin:FacebookLib").projectDir = new File("phonegap-facebook-plugin/enerate-FacebookLib")

Thanks !

**Comment by agamemnus** [comment]
I don't know, sorry. Maybe duplicates?

**Comment by SebDigital** [comment]
couldn't see duplicates but noticed that on the XAPLAlarmReceiver.java
this line is greyout:
import com.google.android.vending.expansion.downloader.DownloaderClientMarshaller;
and it says Unused Import statement. so I don't think it is calling this line and I think this is creating the error...

Thanks!

Seb

**Comment by agamemnus** [comment]
Greyed out where? It's not commented out.

If it's not being used, it wouldn't cause an error. But anyway, you are always free to modify the Java files and try recompiling.

It is definitely an issue with a combination of that plugin and mine. I remember I had some sort of issue with it. I think I deleted a jar file that was duplicating code from the included Google libs.

**Comment by SebDigital** [comment]
Yes it is Android Studio doing it when building apk

Here is the Grable error I have: (for some reasons it can't find or link). Do you rememer the jar file you have deleted and where to find it? thanks

/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKAlarmReceiver.java:8: error: package com.google.android.vending.expansion.downloader does not exist
import com.google.android.vending.expansion.downloader.DownloaderClientMarshaller;
                                                      ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:23: error: package com.google.android.vending.expansion.downloader does not exist
import com.google.android.vending.expansion.downloader.DownloadProgressInfo;
                                                      ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:24: error: package com.google.android.vending.expansion.downloader does not exist
import com.google.android.vending.expansion.downloader.DownloaderClientMarshaller;
                                                      ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:25: error: package com.google.android.vending.expansion.downloader does not exist
import com.google.android.vending.expansion.downloader.DownloaderServiceMarshaller;
                                                      ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:26: error: package com.google.android.vending.expansion.downloader does not exist
import com.google.android.vending.expansion.downloader.Helpers;
                                                      ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:27: error: package com.google.android.vending.expansion.downloader does not exist
import com.google.android.vending.expansion.downloader.IDownloaderClient;
                                                      ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:28: error: package com.google.android.vending.expansion.downloader does not exist
import com.google.android.vending.expansion.downloader.IDownloaderService;
                                                      ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:29: error: package com.google.android.vending.expansion.downloader does not exist
import com.google.android.vending.expansion.downloader.IStub;
                                                      ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:38: error: cannot find symbol
public class XAPKDownloaderActivity extends Activity implements IDownloaderClient {
                                                                ^
  symbol: class IDownloaderClient
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:39: error: cannot find symbol
 private IStub mDownloaderClientStub;
         ^
  symbol:   class IStub
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:40: error: cannot find symbol
 private IDownloaderService mRemoteService;
         ^
  symbol:   class IDownloaderService
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:193: error: cannot find symbol
 @Override public void onDownloadProgress (DownloadProgressInfo progress) {
                                           ^
  symbol:   class DownloadProgressInfo
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderService.java:3: error: package com.google.android.vending.expansion.downloader.impl does not exist
import com.google.android.vending.expansion.downloader.impl.DownloaderService;
                                                           ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderService.java:5: error: cannot find symbol
public class XAPKDownloaderService extends DownloaderService {
                                           ^
  symbol: class DownloaderService
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKAlarmReceiver.java:13: error: cannot find symbol
   DownloaderClientMarshaller.startDownloadServiceIfRequired(context, intent, XAPKDownloaderService.class);
   ^
  symbol:   variable DownloaderClientMarshaller
  location: class XAPKAlarmReceiver
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:57: error: cannot find symbol
  File fileForNewFile = new File(Helpers.generateSaveFileName(ctx, fileName));
                                 ^
  symbol:   variable Helpers
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:70: error: cannot find symbol
   String fileName = Helpers.getExpansionAPKFileName(this, (i == 0), versionList[i]);
                     ^
  symbol:   variable Helpers
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:126: error: cannot find symbol
   int startResult = DownloaderClientMarshaller.startDownloadServiceIfRequired (this, pendingIntent, XAPKDownloaderService.class);
                     ^
  symbol:   variable DownloaderClientMarshaller
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:128: error: cannot find symbol
   if (startResult == DownloaderClientMarshaller.NO_DOWNLOAD_REQUIRED) {Log.v (LOG_TAG, "No download required."); finish (); return;}
                      ^
  symbol:   variable DownloaderClientMarshaller
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:133: error: cannot find symbol
   mDownloaderClientStub = DownloaderClientMarshaller.CreateStub (this, XAPKDownloaderService.class);
                           ^
  symbol:   variable DownloaderClientMarshaller
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:188: error: method does not override or implement a method from a supertype
 @Override public void onServiceConnected (Messenger m) {
 ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:189: error: cannot find symbol
  mRemoteService = DownloaderServiceMarshaller.CreateProxy (m);
                   ^
  symbol:   variable DownloaderServiceMarshaller
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:193: error: method does not override or implement a method from a supertype
 @Override public void onDownloadProgress (DownloadProgressInfo progress) {
 ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:212: error: method does not override or implement a method from a supertype
 @Override public void onDownloadStateChanged (int newState) {
 ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:213: error: cannot find symbol
  Log.v (LOG_TAG, "DownloadStateChanged: " + getString(Helpers.getDownloaderStringResourceIDFromState(newState)) + ".");
                                                       ^
  symbol:   variable Helpers
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:216: error: cannot find symbol
   (newState == STATE_IDLE) ||
                ^
  symbol:   variable STATE_IDLE
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:217: error: cannot find symbol
   (newState == STATE_FETCHING_URL) ||
                ^
  symbol:   variable STATE_FETCHING_URL
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:218: error: cannot find symbol
   (newState == STATE_CONNECTING) ||
                ^
  symbol:   variable STATE_CONNECTING
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:219: error: cannot find symbol
   (newState == STATE_DOWNLOADING) ||
                ^
  symbol:   variable STATE_DOWNLOADING
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:220: error: cannot find symbol
   (newState == STATE_PAUSED_NETWORK_UNAVAILABLE) ||
                ^
  symbol:   variable STATE_PAUSED_NETWORK_UNAVAILABLE
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:221: error: cannot find symbol
   (newState == STATE_PAUSED_BY_REQUEST) ||
                ^
  symbol:   variable STATE_PAUSED_BY_REQUEST
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:222: error: cannot find symbol
   (newState == STATE_PAUSED_WIFI_DISABLED_NEED_CELLULAR_PERMISSION) ||
                ^
  symbol:   variable STATE_PAUSED_WIFI_DISABLED_NEED_CELLULAR_PERMISSION
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:223: error: cannot find symbol
   (newState == STATE_PAUSED_NEED_CELLULAR_PERMISSION) ||
                ^
  symbol:   variable STATE_PAUSED_NEED_CELLULAR_PERMISSION
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:224: error: cannot find symbol
   (newState == STATE_PAUSED_ROAMING)
                ^
  symbol:   variable STATE_PAUSED_ROAMING
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderActivity.java:227: error: cannot find symbol
  if (newState == STATE_COMPLETED) {
                  ^
  symbol:   variable STATE_COMPLETED
  location: class XAPKDownloaderActivity
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderService.java:8: error: method does not override or implement a method from a supertype
 @Override public String getPublicKey () {return BASE64_PUBLIC_KEY;}
 ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderService.java:9: error: method does not override or implement a method from a supertype
 @Override public byte[] getSALT () {return SALT;}
 ^
/Users/sebdigital/Documents/SEBDIGITAL/localserver/eneratenew/enerate/platforms/android/src/com/flyingsoftgames/xapkreader/XAPKDownloaderService.java:10: error: method does not override or implement a method from a supertype
 @Override public String getAlarmReceiverClassName () {return XAPKAlarmReceiver.class.getName();}
 ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
38 errors

**Comment by SebDigital** [comment]
I have this also in the AndroidManifest.xml:
'com.flyingsoftgames.xapkreader.XAPKDownloaderService' is not assignable to 'android.app.Service' less... (⌘F1) 
Validates resource references inside Android XML files.

**Comment by agamemnus** [comment]
I don't remember. Which jar files does it add...?

**Comment by SebDigital** [comment]
I have given up on it :( trying to think on a different way to get the extra files I need for the app to work for now. Thanks for responding, appreciate it
