### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by marcos1954** [agamemnus/cordova-plugin-xapkreader#102]
Error: Failed to fetch plugin https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 235 Error output:
npm WARN package.json com.gayguidevallarta.gayguideapp@0.0.1 No description
npm WARN package.json com.gayguidevallarta.gayguideapp@0.0.1 No repository field.
npm WARN package.json com.gayguidevallarta.gayguideapp@0.0.1 No README data
npm WARN package.json com.gayguidevallarta.gayguideapp@0.0.1 No license field.
npm ERR! addLocal Could not install /var/folders/gs/0w06h4wd5jn71mcby0jsf7dr0000gn/T/npm-46387-71a58a05/git-cache-af1fc05d3cb0/e5432a50e29297438480136718dc93788f507928
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "install" "https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0" "--save"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.6
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/markpage/Developer/GayGuideApp/cordova/node_modules/npm-debug.log

**Comment by agamemnus** [comment]
Doesn't seem related to an issue with my plugin...

**Comment by marcos1954** [comment]
The problem was that cordova 7 is not compatible.  went back to cordova 6.5.0.

**Comment by agamemnus** [comment]
You mean incompatible? That's not good.
