### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by blablapolicja** [agamemnus/cordova-plugin-xapkreader#104]
after running
```cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0``` 
or
```cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader#cordova-6.5.0```
I get
```Error: Failed to fetch plugin https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stanislav_dzhus/.npm/_logs/2017-07-11T20_17_05_649Z-debug.log
```

**Comment by agamemnus** [comment]
I don't know what the problem is. Let me know if you figure it out in this thread: https://github.com/agamemnus/cordova-plugin-xapkreader/issues/103.

**Comment by blablapolicja** [comment]
can you install the plugin with `cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader#cordova-6.5.0`?

**Comment by blablapolicja** [comment]
I'm just trying to figure out, is the problem with npm or cordova?

**Comment by agamemnus** [comment]
I have no clue. I'll try it in a bit.

**Comment by agamemnus** [comment]
This seems to be a problem with differences between Cordova 6.5.0 and 7+ -- downgrading to 6.5.0 allows an installation. Please use the other thread for your findings, if any.

**Comment by blablapolicja** [comment]
thank you
