### ISSUE TITLE
Downloading assets bug

### ISSUE THREAD

**Issue by KennyBarraud** [agamemnus/cordova-plugin-xapkreader#107]
Hi !
I got a bug when I use my signed apk.
It displays a dialog "downloading assets" then my app fails to execute.
I have also a download bar at 0mb/0mb.
When I check the error report on Google Play Console it says [this](http://i.imgur.com/mXnh2dQ.jpg) .
What I have done wrong ?
Do I need to change these variables ?

```
<variable name="XAPK_TEXT_DL_ASSETS" value="Downloading assets…" />
<variable name="XAPK_TEXT_PR_ASSETS" value="Preparing assets…" />
<variable name="XAPK_TEXT_DL_FAILED" value="Download failed." />
<variable name="XAPK_TEXT_ERROR" value="Error." />
<variable name="XAPK_TEXT_CLOSE" value="Close." />
<variable name="XAPK_MAIN_VERSION" value="0" />
<variable name="XAPK_PATCH_VERSION" value="0" />
<variable name="XAPK_MAIN_FILESIZE" value="0" />
<variable name="XAPK_PATCH_FILESIZE" value="0" />
<variable name="XAPK_AUTO_DOWNLOAD" value="true" />
<variable name="XAPK_PROGRESS_FORMAT" value="percent" />
```

**Comment by agamemnus** [comment]
Did you specify a public key?

Possibly related to https://github.com/agamemnus/cordova-plugin-xapkreader/issues/94.

**Comment by KennyBarraud** [comment]
Yes I have set the public key with the one in the Google Play Console give in Base64 in the Services & APIs menu.

Litte precision : It happens only with a signed apk, not with the debug one. The test device is on Android 7.0. I was triying to follow [this tutorial](https://iphonedevlog.wordpress.com/2014/12/12/adding-an-android-apk-expansion-file-to-a-cordova-project/).

**Comment by KennyBarraud** [comment]
Ok so I solved the issue !
The fact is that the public key was set in the config.xml file but not in the android.json of the cordova plugin folder. Other error is when you set the key when you add the plugin in command line => The result is that there are two "XAPK_PUBLIC_KEY" variable and the build fails.
