### ISSUE TITLE
 Problem when starting the application

### ISSUE THREAD

**Issue by DenisVedin** [agamemnus/cordova-plugin-xapkreader#108]
Good afternoon.
There are problems when working with the plugin. During the testing of the application, there is an infinite download of the add-on file, i.e. When you launch it, application is trying to download the file, an error message appears immediately, and in the notification pane there is a message about downloading of the file with the size of -0.00MB / -0.00MB (Screenshots are attached).
![screenshot_2017-08-09-11-49-46](https://user-images.githubusercontent.com/26786576/29111026-333e07b0-7d02-11e7-9a41-3f1a9b4d4b91.png)
![screenshot_2017-08-09-11-49-30](https://user-images.githubusercontent.com/26786576/29111030-364536f4-7d02-11e7-84be-c36b10b6a248.png)

**Comment by DenisVedin** [comment]
Thanks, the question is solved. It was necessary to add `XAPK_PUBLIC_KEY` in `config.xml` and `XAPK_PATCH_VERSION: -1` in `android.json`.

**Comment by stihl-sicher** [comment]
Hi,
I run into the same issue. I tried the suggested changes (public key was already there but patch-version was set to 0. So I changed this to -1.
App still tries to download asset which fails and infinite download remains.
@DanteShade: could you share your other settings in config.xml
And which URL do you use to load content from the expansion file?

Best regards,

**Comment by stihl-sicher** [comment]
Well, I have to change my error description: I changed the XAPK_PATCH_VERSION to -1 
but when I run the build process, the value is set to 0 automatically.
Is there another place to set these options? 
Do I have to set "XAPK_MAIN_VERSION"?

**Comment by agamemnus** [comment]
android.json

**Comment by stihl-sicher** [comment]
Hi, 
thanks for your fast reply @agamemnus 
I have changed values in android.json but config.xml ist still "corrected" to 0. :(

This is my part from config.xml:
```
    <plugin name="com.flyingsoftgames.xapkreader" spec="https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0">
        <variable name="XAPK_EXPANSION_AUTHORITY" value="eu.mapone.badreichenhall.expansion" />
        <variable name="XAPK_PUBLIC_KEY" value=".....my Base64 String from Store....." />
        <variable name="XAPK_TEXT_DL_ASSETS" value="Downloading assets…" />
        <variable name="XAPK_TEXT_PR_ASSETS" value="Preparing assets…" />
        <variable name="XAPK_TEXT_DL_FAILED" value="Download failed." />
        <variable name="XAPK_TEXT_ERROR" value="Error." />
        <variable name="XAPK_TEXT_CLOSE" value="Close." />
        <variable name="XAPK_MAIN_VERSION" value="0" />
        <variable name="XAPK_PATCH_VERSION" value="0" />
        <variable name="XAPK_MAIN_FILESIZE" value="0" />
        <variable name="XAPK_PATCH_FILESIZE" value="0" />
        <variable name="XAPK_AUTO_DOWNLOAD" value="true" />
        <variable name="XAPK_PROGRESS_FORMAT" value="percent" />
    </plugin>

```
How do I reference an image in the expansion file?
I have found:
`content://eu.mapone.badreichenhalltest.expansion/main_expansion/`
as a preline to the image path where eu.map.....est.expansion is related to the value "XAPK_EXPANSION_AUTHORITY".

Best regards!

**Comment by agamemnus** [comment]
No, just `<img src="content://eu.mapone.badreichenhalltest.expansion/myfile.png">`.

**Comment by agamemnus** [comment]
You might need to remove the build files to get that -1 to stick. Not sure.

**Comment by stihl-sicher** [comment]
I had already removed and added android as platform. Without success.
Changing the values in package.json in apps main folder did the change.

Thanks for your reply, @agamemnus!

**Comment by stihl-sicher** [comment]
I have tried several combinations of settings now... My last configuration:
```
    <plugin name="com.flyingsoftgames.xapkreader" spec="https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0">
        <variable name="XAPK_EXPANSION_AUTHORITY" value="eu.mapone.badreichenhalltest.expansion" />
        <variable name="XAPK_PUBLIC_KEY" value=".....my Base64 String from Store....." />
        <variable name="XAPK_TEXT_DL_ASSETS" value="Downloading assets…" />
        <variable name="XAPK_TEXT_PR_ASSETS" value="Preparing assets…" />
        <variable name="XAPK_TEXT_DL_FAILED" value="Download failed." />
        <variable name="XAPK_TEXT_ERROR" value="Error." />
        <variable name="XAPK_TEXT_CLOSE" value="Close." />
        <variable name="XAPK_MAIN_VERSION" value="2" />
        <variable name="XAPK_PATCH_VERSION" value="-1" />
        <variable name="XAPK_MAIN_FILESIZE" value="144" />
        <variable name="XAPK_PATCH_FILESIZE" value="0" />
        <variable name="XAPK_AUTO_DOWNLOAD" value="false" />
        <variable name="XAPK_PROGRESS_FORMAT" value="percent" />
    </plugin>
```
This prevented the download problem but I can not open the images contained in the expansion file.
All configurations before with AUTO_DOWNLOAD=TRUE resulted in an download error.
Do I have to input a number in MAIN_VERSION? And in which format (if?) do I have to place the filesize?

I suppose/hope the file should be present since the app size from store has about 160 MB which is the size of APK and expansion file combined...

Best regards,
stihl-sicher

**Comment by agamemnus** [comment]
No, there is no need to change that from 0. I don't know what's happening
here. Try making a test app without any modifications, the simplest you
can, and go from there.

**Comment by stihl-sicher** [comment]
Thanks for your answer. I have disabled automatic download now.
Since I created an folder "main_expansion" to collect all data for expansion file and compressed this folder, I have to note this foldername in my file url.
No I can see my pictures and maptiles.
