### ISSUE TITLE
Download success, but content not visible until there's a restart.

### ISSUE THREAD

**Issue by git00** [agamemnus/cordova-plugin-xapkreader#11]
First off, thanks for putting this together!  It's the first plugin for this that seems workable to me.  I found out about this from a blog post (http://iphonedevlog.wordpress.com/2014/12/12/adding-an-android-apk-expansion-file-to-a-cordova-project/), and I've been working to see if I can get the downloading to work properly.  I've also posted to the Google Groups for Phonegap about this, so I'll re-post my question from there:

Okay, I've been playing around with this plugin some more and the re-downloading code does actually work.  The issue is in the XAPKReader.reloadExpansionFile function.  The try block will crash the app.  If it's commented out (and you've set the metadata for your main and patch file versions and filesizes), it will properly do the download of the needed expansion files (I tested with deleting just the main, just the patch, and both) and they all re-download.  The issue is that the plugin asynchronously calls the downloader activity then immediately allows the cordova webview to load, so if the expansion files do need to be downloaded/re-downloaded, your webview has already loaded and doesn't know that the expansion files are now there.  Depending on which files were still on your device, the app may look like it doesn't have any expansion files or only has the main file.  You have to shut down the app, and restart it again before it will show files from the expansion files.

I'm not a Java expert, but I figure a RunnableFuture or a FutureTask would enable the plugin to block and wait for confirmation that the expansion files are available before allowing the cordova webview to proceed.  Any Android/Java experts able to lend a hand with the code?  If the Runnable could be changed to wait for completion before running the super.initialize line, I think it might be enough.

Code below (from the `XAPKReader.java` file in the `initialize` function):
```java
  cordova.getActivity().runOnUiThread (new Runnable() {
   @Override public void run () {
    Context context = cordova.getActivity().getApplicationContext();
    Intent intent = new Intent(context, XAPKDownloaderActivity.class);
    intent.putExtras (bundle);
    cordova.getActivity().startActivity (intent);
   }
  });
  
  super.initialize (cordova, webView);
```
Alternatively, does anyone know how to force the cordova webview to restart from the top?

**Comment by agamemnus** [comment]
An automatic re-download of the expansion files (if they are missing) is not a normal circumstance. I'm guessing that 99.999% of users won't ever do that.

So at this point it's an academic exercise, but I don't know enough to fix this at the moment.

**Comment by agamemnus** [comment]
Ok, I'm still recovering from a lot of hacking and coughing. Let's try to solve this. I'm still pretty fuzzy about everything, (including this plugin!) so let's go step by step...

* You say that the try block in ``reloadExpansionFile`` crashes the app. Why does it crash the app?

* You comment it out? The entire ``reloadExpansionFile`` function or the outer ``try``.. ``catch``? I assume you comment out the whole thing?

* Asynchronously calling the ``XAPKDownloaderActivity``? I think I understand the problem now.

Why are we calling
````
 @Override public void run () {
Context context = cordova.getActivity().getApplicationContext();
Intent intent = new Intent(context, XAPKDownloaderActivity.class);
intent.putExtras (bundle);
cordova.getActivity().startActivity (intent);
}
````
.... asynchronously again? I guess it's because we assume the files are already there? Does it matter if it's asynchronous? Maybe it's better to remove the asynchronous stuff here.. would that work?

**Comment by git00** [comment]
I did comment out the entire function `reloadExpansionFile` as well as all calls to it, so the app will now continue and load up normally.

`XAPKDownloaderActivity` implements `IDownloaderClient` which is asynchronous in nature. It checks to see if the files are already available, and if not, it triggers the downloading sequence.  The activity should only be marked as complete after it either (1) finds that the files are already available initially, (2) finds that `DownloaderClientMarshaller.NO_DOWNLOAD_REQUIRED` is true, or (3) after it reaches `STATE_COMPLETED` in the `onDownloadStateChanged` function.

I put breakpoints on the `super.initialize (cordova, webView);` call in `XAPKReader` as well as the first statement in the `onCreate` function of `XAPKDownloaderActivity`, and I can see it reaching the `super.initialize (cordova, webView);` call before it gets to the `onCreate` function of `XAPKDownloaderActivity`.

I tried to various ways of making it wait, but I must not understand `FutureTask` completely:
```java
  FutureTask<Void> ft = new FutureTask<Void> (new Runnable() {
      @Override public void run () {
          Context context = cordova.getActivity().getApplicationContext();
          Intent intent = new Intent(context, XAPKDownloaderActivity.class);
          intent.putExtras (bundle);
          cordova.getActivity().startActivity (intent);
      }
  }, null);
  cordova.getActivity().runOnUiThread(ft);

  try {
	  ft.get();
	  cr.call (Uri.parse("content://" + expansionAuthority), "set_expansion_file_version_data", null, bundle);
	  super.initialize (cordova, webView);
  } catch (InterruptedException e) {
      throw new RuntimeException("Interrupted waiting for FutureTask", e);
  } catch (ExecutionException e) {
      throw new RuntimeException("Interrupted waiting for FutureTask", e);
  }
```

**Comment by agamemnus** [comment]
So is that right at 92, or before 104 and 172 in https://github.com/agamemnus/cordova-plugin-xapkreader/blob/gh-pages/src/android/XAPKDownloaderActivity.java? Right?

What do you think of calling a completion function within ``XAPKDownloaderActivity.java`` which will then call a static function in ``XAPKReader.java`` that will then run ``super.initialize (cordova, webView);``?

**Comment by git00** [comment]
Almost, the three spots I meant were actually line 69 (which I made multi-line), line 92 (which I made multi-line), and before line 172.

I think I tried your suggested solution, but couldn't figure out a way to do it as `cordova` and `webView` are passed into the `initialize` function and `super.initialize` should be called from within the `initialize` function.

Academically speaking, those would be the three spots, but practically, it's really only before 172.  This is the only case where the files were either missing or not current before the app started.

**Comment by agamemnus** [comment]
Why can't we save ``cordova``, ``webView``, and ``super`` for use later? I'm going to try this soon...

**Comment by git00** [comment]
I couldn't figure out a way to use super in a static function, but maybe you'll have better luck.

**Comment by agamemnus** [comment]
I believe that this has been fixed a month or so ago, so I am closing the issue.
