### ISSUE TITLE
Issue when load image from OBB folder with dynamic image name.

### ISSUE THREAD

**Issue by bhavika162** [agamemnus/cordova-plugin-xapkreader#118]
Hello,

I am using OBB folder to load image with dymaic name, but image doesn't display after creating build. I had display the image name with full path, it's showing me with proper name.
e.g. image path : <img src="content://ch.texst.app.nm/assets/img/image1_'{{config.name}}'.png">

When I print the image path, it's showing fine but It is not displaying image.

FYI, I am using  cordova-plugin-xapkreader v6.5.0.

Please let me know if anyone has worked on this issue.
Thanks in advance.

**Comment by agamemnus** [comment]
What is a "dynamic name"???

What is the path that you used? ... needs more details.

**Comment by bhavika162** [comment]
So if I keep static image path like this
img src="content://com.app.myapp/assets/img_john.png"
I am able to get image from zip/obb.

But if I try to get image like this 
img src="content://com.app.myapp/assets/img_{{ this.config.userName }}.png"
I am not getting image.

**Comment by agamemnus** [comment]
That is a bug on your end... I'm pretty sure, anyway.. Try console logging
what strings you send.

**Comment by lolaswift** [comment]
> Hello,
> 
> I am using OBB folder to load image with dymaic name, but image doesn't display after creating build. I had display the image name with full path, it's showing me with proper name.
> e.g. image path :
> 
> When I print the image path, it's showing fine but It is not displaying image.
> 
> FYI, I am using cordova-plugin-xapkreader v6.5.0.
> 
> Please let me know if anyone has worked on this issue.
> Thanks in advance.

have you found any solution?

**Comment by lolaswift** [comment]
@bhavika162 Have you found any solution?

**Comment by agamemnus** [comment]
This doesn't have anything to do with the plugin though. The plugin doesn't just somehow read the HTML file and determine if something is generated in Javascript or not.

**Comment by lolaswift** [comment]
All right. Here is the solution if you use ionic 3:
1. .ts
import { DomSanitizer } from '@angular/platform-browser';
  constructor(
    public _sanitizer: DomSanitizer,
  }
2. .html
        <img [src]="_sanitizer.bypassSecurityTrustResourceUrl(images[i])" />

@agamemnus Thank you for this great plugin. Thank you for your contribution to the open source world. You're a great man!  This repo deserves more stars! --Cheers,Lola

**Comment by agamemnus** [comment]
Thanks. Happy you found the solution! 👍
