### ISSUE TITLE
public API key

### ISSUE THREAD

**Issue by BobAchgill** [agamemnus/cordova-plugin-xapkreader#123]
Sorry for the Newby question... 
Is it enough to just copy/paste the Google Play Public key to replace ""Your Google Play public API key"" ??

```
<plugin name="com.flyingsoftgames.xapkreader" spec="https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0">
        <variable name="XAPK_PUBLIC_KEY" value="Your Google Play public API key" />
    </plugin>
```

Because when I run ...

`cordova build android --release`

I only find an unsigned release apk.

**Comment by agamemnus** [comment]
Latest version should let you set that on install. Replacing it within the
plugin install doesn't do anything unless you clear all generated code.

**Comment by BobAchgill** [comment]
> unless you clear all generated code

by this you mean going back to the Create project step?

`cordova create MyProject`
   copied in my config.xml with the Google Play public key value set
`cordova platform add android@5.1.1`
`cordova build android --release`

... and still got an unsigned release apk.

**Comment by agamemnus** [comment]
Wait, unsigned release APK? That's not what signs it. Read this:

https://ionicframework.com/docs/v1/guide/publishing.html
