### ISSUE TITLE
Tips on Debugging

### ISSUE THREAD

**Issue by chipbell4** [agamemnus/cordova-plugin-xapkreader#127]
Hello again,

This is not necessarily a bug that I've found, but I question TBH. I'm almost positive I've misconfigured something, and I was curious if you had any tips for debugging things once they're in Google Play Beta. I don't fully understand every line of code here, but it appears that much of the code isn't actually executed unless the app is delivered in Google Play (as opposed to a side-loaded build).

Aside from adding tons of `Log.v` calls everywhere, do you have any tips for tracking down problems?

My particular issue: I'm seeing the initial install of my particular app crash when running the Downloader Activity. I submitted a PR to fix it yesterday, but now it appears the activity just hangs. I'd like to triage myself and confirm that it's either 1) My poor configuration or 2) A bug in the app (which I can promptly fix and PR 👍 )

**Comment by agamemnus** [comment]
Just have to log things; don't know a better way to do it.

**Comment by agamemnus** [comment]
I mean, you can look at the stack of course... that could help.

**Comment by chipbell4** [comment]
Absolutely, and for exceptions that has been helpful. I was afraid logging would have been the best way. The Android docs on the process hint at that method, and I didn't see another way. Either way, I'll keep digging and send a PR your way if I find something. I'll close this too. Thanks again!

**Comment by chipbell4** [comment]
Oh, and for those who find this thread later. You're going to need `Log.i` instead of `Log.v`. I think the verbose calls are stripped in the store. FYI.
