### ISSUE TITLE
Unable to read files from within OBB file

### ISSUE THREAD

**Issue by Sake-tan** [agamemnus/cordova-plugin-xapkreader#13]
When I try to read an image with the following pathing "content://my.cordova.project/assets/images/Example.png", I receive a 404 upon inspecting during launch.

I placed my obb file in Phone\Android\obb\my.cordova.project\main.0001.my.cordova.project.obb. The obb file itself is a simple, 0 compression zip containing assets I wish to load. Inside the obb file is a single folder called Assets, which then leads to images, music, etc.

I saw that there was an issue alike this one, but most of the fixing went via private messaging, so I'm unaware of the solution, still.

**Comment by agamemnus** [comment]
There isn't any private messaging here.

I'm not sure if capitalization matters, but try to use lowercase directories and folders.

I can take a look at your example project if you upload it somewhere.

**Comment by Sake-tan** [comment]
I'm not sure if I can share the project, but I'll try to explain what I did on a step by step basis, if that helps at all.

Basically, what I did:

1 Installed the plugin
2 replaced the package names in the xapkreader.xml manually, as I am running Crosswalk, and my project does not have the ant-build and ant-gen files.
3 Modified the project.properties
4 Modified the android.json, but did not change the license key as I am only testing locally for now.
5 STORED the entire asset folder in a zip, and renamed it to main.0001.my.cordova.project.obb, placing it on the phone manually in the folder specified above
6 Changed the paths to the assets as described above


I didn't change anything else, is there something I'm missing?

**Comment by agamemnus** [comment]
1) Did you set xapk_expansion_authority to "my.cordova.project"?
2) Triple-check that your zip file is a STORE.
3) Make sure your zip file really starts with assets/.
4) Capitalization might matter.
5) Are you using Cordova, then migrating Crosswalk into the platform directory, or...?

**Comment by Sake-tan** [comment]
1 Yes, I set the authority to my.cordova.project in line 100 of the android.json file located in "(project root folder)/cordova/plugins". I also changed it within the xapkreader.xml file located in "(project root folder)/res/values/"

2 My zip file is a STORE

3 The zip file starts with the assets folder, I simply right clicked the assets folder and created a new archive from the right click menu

4 I'm using the right capitalization for everything. The Android and Phone folders on the mobile device are by default capitalized, however I am using content:// to access the obb file within the phone storage (not the SD card?)

5 I created the project using the Codova Android (ARM) found on the following page: https://crosswalk-project.org/documentation/downloads.html


Are there any steps I might have missed setting the project up?

**Comment by agamemnus** [comment]
Is the app itself named my.cordova.project?

You should just create a sample project with a single image and a very simple index.html file loading that image. Then it will likely become obvious.

You might also want to look at this:
https://github.com/agamemnus/cordova-plugin-xapkreader/issues/9

**Comment by Sake-tan** [comment]
The app itself is still called CordovaExample. Am I to change that to my.cordova.project?
I will rename it or change the obb directory to CordovaExample to see if I get any results.

I'll create a sample project as you said and see what the results are.

I took a look at the issue earlier as well, but didn't really understand (as some things might have been exchanged via e-mail), but from what I gather it has to do with the obb directory name. I'll do that and post results.

**Comment by agamemnus** [comment]
The app id, I mean. The obb filename should be named following the app id.

**Comment by Sake-tan** [comment]
If by ID you mean package name, then yes, they are both my.cordova.project. The app shows up as CordovaExample on the phone, though.

**Comment by agamemnus** [comment]
Ok, I'll wait for your sample project...

**Comment by Sake-tan** [comment]
Sorry for the long wait, I created an example project that loads a single image from an obb file. I uploaded the example project, OBB and APK in this rar: http://puu.sh/fmUNN/eade858a21.rar
As you can see, it works. I don't know why it's not working on my main project, the only thing that might be different is the folder structure, which I believe I got right
OBB structure:
* main.1.my.cordova.project.OBB (Zip file, store)
 * assets
   * sound
     * contents of sound folder
    * images
      * contents of images folder
    * config
      * contents of config folder


If I need to manifest an image, for example, I use the following: 
manifest: [
		{src:"content://my.cordova.project/assets/images/Flag.png", id:"Flag"},

**Comment by Sake-tan** [comment]
Quick update, I believe I got it working on my main project as well. The problem was probably that I had some config files it requires during loading in the app. When I kept those in the main project, everything worked as intended.

**Comment by agamemnus** [comment]
You can change all instances of "com.example.expansion"... but, I'm glad you got it working.
