### ISSUE TITLE
Failed to test remotely through the Google Playstore

### ISSUE THREAD

**Issue by lolaswift** [agamemnus/cordova-plugin-xapkreader#135]
Need some help to troubleshoot.

Local debug works ok but remote not, I was following http://www.clearlyinnovative.com/my-apk-is-too-big to do the remote test.
  
Although,  "Expansion file check/download success." was printed, but no expansion file downloaded from google play store.

I use these code:
=========================================================================
    if (window["XAPKReader"]) {

        window["XAPKReader"].downloadExpansionIfAvailable(function () {
          console.log("Expansion file check/download success.");
        }, function (_error) {
          console.error(_error);
        });
      }
=========================================================================

**Comment by agamemnus** [comment]
--> "6.5 At the bottom of the APK upload modal, you’ll notice a drop-down list labeled Use expansion file (This will only appear if the APK you’re submitting is for an update)"

You have to submit it twice to actually upload it. Then, I don't know if it's instant. Check if the file is physically in your phone...

**Comment by lolaswift** [comment]
@agamemnus thanks for the tips. I am waiting for google to approve my alpha test.
Just a question, in the code above, the first callback will only print out "Expansion file check/download success." if the file has been downloaded successfully? The result of my last test was the obb folder was created by no .obb file was downloaded.

The first time user install the app, the apk and the obb file will be downloaded together first,  and then my app will start launching?

If somehow, the oob was missing, and when the above code starts downloading .obb, will user get a dialog? I should delay my app from entering the main interface because my data isn't ready yet?
Sorry for silly questions. I have no previous experience with these. Need to figure out the logic I need to implement.

Just another one. The article I was following didn't add the public key during the installation of the plugin? will that cause any issues?

**Comment by agamemnus** [comment]
If there's no obb per Google, it should do a success as well.

Theoretically.

**Comment by lolaswift** [comment]
![screen shot lp](https://user-images.githubusercontent.com/5462925/49088742-38e04380-f25a-11e8-99f5-9d08e5d99d4e.png)

**Comment by lolaswift** [comment]
The above screenshot was what Google support team sent to me. I submitted my app for alpha test but got rejected.

**Comment by lolaswift** [comment]
@agamemnus Do you know why I always get "Expansion file check/download success." even if I don't have any expansion file on the play store?

**Comment by agamemnus** [comment]
Yes, like I said: "success" means that there was a file check and the file was downloaded if it existed or was not downloaded if it didn't exist. (A failure would be a download attempt when the file existed.)

**Comment by agamemnus** [comment]
They are probably using the wrong Cordova settings.

**Comment by agamemnus** [comment]
Please check https://github.com/agamemnus/cordova-plugin-xapkreader/pull/136.
