### ISSUE TITLE
Opening other type of files

### ISSUE THREAD

**Issue by djm56** [agamemnus/cordova-plugin-xapkreader#14]
Hi I have everything working, and can use most of the files in the obb file.
My obb file contains a lot of other type of documents .doc .xls etc.
I need to be able to open these files in some way and for the life of me could not figure out. I tried to just link to them but this did not work.

So I thought maybe I should copy the files out of the obb file to the sdcard and then I can view these documents, but I can't get the copy to happen. Maybe not the right way but thought I would just try.

Here is the code I used
```javascript
function onDeviceReadyMe() {
    window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, onFileSystemSuccess, fail);
    window.resolveLocalFileSystemURL("content://za.co.anomalous.cfourk/main_expansion/5/uploads/booklets/O2.doc", 
    		function(entry) 
    {
        window.resolveLocalFileSystemURL("file:///sdcard/", 
        function(destination) {
             entry.copyTo(destination,"O2.doc",success,fail);
        })
    });
}
```
But I keep getting these errors

02-03 12:43:35.280: D/dalvikvm(24792): GC_CONCURRENT freed 7575K, 22% free 30285K/38599K, paused 3ms+102ms
02-03 12:43:35.490: W/System.err(24792): java.io.FileNotFoundException
02-03 12:43:35.490: W/System.err(24792): 	at com.flyingsoftgames.xapkreader.XAPKProvider.openAssetFile(XAPKProvider.java:115)
02-03 12:43:35.500: W/System.err(24792): 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:951)
02-03 12:43:35.500: W/System.err(24792): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:337)
02-03 12:43:35.500: W/System.err(24792): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:607)
02-03 12:43:35.500: W/System.err(24792): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:536)
02-03 12:43:35.500: W/System.err(24792): 	at org.apache.cordova.CordovaResourceApi.openForRead(CordovaResourceApi.java:272)
02-03 12:43:35.500: W/System.err(24792): 	at org.apache.cordova.CordovaResourceApi.openForRead(CordovaResourceApi.java:231)

Where could I be going wrong? Any help would be appreciated this is probably the wrong forum to ask but could not figure out where else I could ask.

**Comment by agamemnus** [comment]
What happens when you link to them and then open to them in the app without this code?

**Comment by djm56** [comment]
Wow thanks for the quick response

This is what I get by just using a href

2-03 13:23:31.630: E/webkit(17408): Exception: content://za.co.anomalous.cfourk/main_expansion/5/uploads/booklets/O2.doc
02-03 13:23:32.010: D/CordovaWebViewClient(17408): CordovaWebViewClient.onReceivedError: Error code=-10 Description=The protocol is not supported. URL=content://za.co.anomalous.cfourk/main_expansion/5/uploads/booklets/O2.doc
02-03 13:23:32.010: D/CordovaActivity(17408): onMessage(onReceivedError,{"errorCode":-10,"url":"content:\/\/za.co.anomalous.cfourk\/main_expansion\/5\/uploads\/booklets\/O2.doc","description":"The protocol is not supported."})
02-03 13:23:32.110: D/CordovaWebViewClient(17408): onPageStarted(content://za.co.anomalous.cfourk/main_expansion/5/uploads/booklets/O2.doc)
02-03 13:23:32.110: D/CordovaActivity(17408): onMessage(onPageStarted,content://za.co.anomalous.cfourk/main_expansion/5/uploads/booklets/O2.doc)
02-03 13:23:32.110: D/CordovaWebViewClient(17408): onPageFinished(content://za.co.anomalous.cfourk/main_expansion/5/uploads/booklets/O2.doc)
02-03 13:23:32.110: D/CordovaActivity(17408): onMessage(onPageFinished,content://za.co.anomalous.cfourk/main_expansion/5/uploads/booklets/O2.doc)

And this is what I get when I using window.open

02-03 13:26:49.350: D/CordovaActivity(17408): onMessage(onReceivedError,{"errorCode":-10,"url":"content:\/\/za.co.anomalous.cfourk\/main_expansion\/5\/uploads\/booklets\/O2.doc","description":"The protocol is not supported."})

Keeps saying the protocol is not supported I also tried a file open plugin I found
https://github.com/markeeftb/FileOpener

But this did not work either

Thanks again for the quick response

**Comment by agamemnus** [comment]
Don't know.

Do you have InAppBrowser installed?

Have you tried loading the bytes with AJAX?

**Comment by djm56** [comment]
Thanks for the help.
I got a quick workaround without using InAppBrowser, every way I tried it the files just did not open. I could get images and html files to open but .doc and other documents could not.
As it needs an external program to open, I had read somewhere that the two apps were not in the same sandbox so just could not see the files I was trying to open.

I used the code above to copy the files I needed from the obb file to the sdcard, then open the files using fileopener plugin to open the files from the sdcard.

https://github.com/markeeftb/FileOpener

```javascript
function onDeviceReadyMe() {
    window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, onFileSystemSuccess, fail);
    window.resolveLocalFileSystemURL("content://za.co.anomalous.cfourk/main_expansion/5/booklets/olympics1.doc", 
    		function(entry) 
    {
        window.resolveLocalFileSystemURL("file:///sdcard/", 
        function(destination) {
             entry.copyTo(destination,"olympics1.doc",success,fail);
        })
    });
}
function success(entry) {
   
    window.plugins.fileOpener.open("file:///" + entry.fullPath);
}
function fail(error) {
    alert(error.code);
}
```
I am sure there is a cleaner solution, but I hope this helps someone else.

Thanks for the help

**Comment by agamemnus** [comment]
To clarify, did you try just with the InAppBrowser built-in plugin?

**Comment by agamemnus** [comment]
This seems to be (possibly) a problem with old Cordova versions (sub-4, or less), so I am closing this issue.
