### ISSUE TITLE
Spaces in Filenames and Folders

### ISSUE THREAD

**Issue by djm56** [agamemnus/cordova-plugin-xapkreader#15]
Once again great plugin.

I have picked up an issue with spaces in File names and Folders.

My App, I have taken a clients CD version of their product and placed all the files in a OBB file, but there are spaces in the directory structure of the CD. There are hundreds of examples like this on my CD.
**Example:**
content://za.co.anomalous.cfourk/main_expansion/5/Templates/store/7/Ad Campaign Template.ppt

**I thought it could be an encode issue so I tried this.**

encodeURI("content://za.co.anomalous.cfourk/main_expansion/5/Templates/store/7/Ad Campaign Template.ppt")

This would put a %20 where ever there was a space but I still got the same error

java.io.FileNotFoundException
W/System.err(10908): 	at com.flyingsoftgames.xapkreader.XAPKProvider.openAssetFile(XAPKProvider.java:115)
02-05 11:15:33.389: W/System.err(10908): 	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:951)
02-05 11:15:33.389: W/System.err(10908): 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:337)
02-05 11:15:33.399: W/System.err(10908): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:607)
02-05 11:15:33.399: W/System.err(10908): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:536)
02-05 11:15:33.399: W/System.err(10908): 	at org.apache.cordova.CordovaResourceApi.openForRead(CordovaResourceApi.java:272)
02-05 11:15:33.399: W/System.err(10908): 	at org.apache.cordova.CordovaResourceApi.openForRead(CordovaResourceApi.java:231)
02-05 11:15:33.399: W/System.err(10908): 	at org.apache.cordova.file.ContentFilesystem.readFileAtURL(ContentFilesystem.java:229)
02-05 11:15:33.399: W/System.err(10908): 	at org.apache.cordova.file.Filesystem.copyFileToURL(Filesystem.java:121)
02-05 11:15:33.399: W/System.err(10908): 	at org.apache.cordova.file.LocalFilesystem.copyFileToURL(LocalFilesystem.java:524)
02-05 11:15:33.399: W/System.err(10908): 	at org.apache.cordova.file.FileUtils.transferTo(FileUtils.java:715)
02-05 11:15:33.399: W/System.err(10908): 	at org.apache.cordova.file.FileUtils.access$10(FileUtils.java:698)
02-05 11:15:33.399: W/System.err(10908): 	at org.apache.cordova.file.FileUtils$22.run(FileUtils.java:494)
02-05 11:15:33.399: W/System.err(10908): 	at org.apache.cordova.file.FileUtils$25.run(FileUtils.java:577)
02-05 11:15:33.399: W/System.err(10908): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-05 11:15:33.409: W/System.err(10908): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)

I tired a few other tests
string.replace(" ","%20");
string.replace(" ","\\ ");

But no joy

It could be a simple fix but have run out of time so just putting this here for your information, I decided to write a script to replace all the " " with "_" in the obb file to avoid the space issues. Maybe should have thought of that in the beginning, but maybe someone in the future wont have direct control over the obb file.

Thanks

**Comment by agamemnus** [comment]
There must be a solution to this. But yeah, I didn't notice this because I have a pavolvian reflex not to use spaces in filenames... guess in your case it is not quite programmers who named those files. I will put it on the TODO list!

**Comment by djm56** [comment]
Agreed I have not used spaces in years.
But just in case someone faces an issue before the fix.

Here is the command I used in Powershell to rename all spaces to underscore. 
```powershell
Get-ChildItem $path |
    Where-Object { $_.Name.Contains(' ') } |
    Rename-Item -NewName { $_.Name -replace ' ', '_' }
```
Will see what the command is on my Mac

**Comment by agamemnus** [comment]
I saw something about spaces recently that explained this problem.

I did a search just now and couldn't find the text I saw before, but found this: http://stackoverflow.com/questions/25977116/phonegap-getpicture-method-fails-when-image-file-names-with-spaces-in-android ... looks like possibly a bug in Cordova.

**Comment by agamemnus** [comment]
Closing this issue. URL encoding is needed to reference files with spaces.

**Comment by okwei2000** [comment]
any updates? facing the same issue when using the File plugin to read a file which space in names.

**Comment by agamemnus** [comment]
Did you try url encoding the filename?

**Comment by okwei2000** [comment]
yes, tried encodeURI(), also tried to replace the space with "\ " or "+".

try
    window.resolveLocalFileSystemURI("content://za.co.anomalous.cfourk/main_expansion/5/Templates/store/7/Ad Campaign Template.ppt", function(){}, function(){
});

**Comment by agamemnus** [comment]
Try "%20" for spaces. Also, try seeing if removing capitals on both ends helps: http://stackoverflow.com/questions/6502712/isnt-android-file-exists-case-sensitive...
