### ISSUE TITLE
Copy File from obb to fileSystem

### ISSUE THREAD

**Issue by Storchissimo** [agamemnus/cordova-plugin-xapkreader#25]
Hy,

I have to copy video and audio files from inside the obb-File to the File-System. Otherwise Android 4.4.4 can't play videos / audio files. 

How can I access a single file in obb-File and copy it to a folder in Filesystem?

**Comment by agamemnus** [comment]
You can use the fileTransfer plugin: https://github.com/apache/cordova-plugin-file-transfer.
