### ISSUE TITLE
Which versions of Cordova is this plugin compatible with?

### ISSUE THREAD

**Issue by lumierephoto** [agamemnus/cordova-plugin-xapkreader#28]
Which versions of Cordova is this plugin compatible with?

I'm using Cordova 4.0 and can't get it working. I can upload the APK to the store and the expansion pack, but when I install it says "Download Failed"

I tried reverting back to an earlier version with:

sudo npm install -g cordova@3.6.3-0.2.13

But that command isn't working on my system. I have Node 4.0

**Comment by agamemnus** [comment]
The current gh-pages (and master) version is for any version that does not use the Gradle build system. 

When you install an app, you should receive an APK from Google Play at the same time, so if you are not getting the obb file, that doesn't have anything to do with the plugin. If you delete the obb file and reinstall a version of your app that's not downloaded from Google Play, you will not receive a new obb download.

**Comment by lumierephoto** [comment]
I am downloading both the APK and the expansion file to the device, but when I open it it says "Download Failed". I know this because of the size of the file.

I'm doing everything command line, so I'm not getting any logs. 

I've combed through everything in this project, but can't get it working. Can you take a look at my project and see if I'm missing something?

 https://www.dropbox.com/sh/kjvom7upeoza8at/AADZugNqCgu-AwwdCqVuxpMNa?dl=0

I will try the Cordova 5.3.1 branch. How would I install that branch in the Cordova project?

Like this?  

cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-5.3.1

**Comment by agamemnus** [comment]
Yes. The readme instructions have been modified for 5.3.1. (see step 6)

**Comment by agamemnus** [comment]
'I am downloading both the APK and the expansion file to the device, but when I open it it says "Download Failed". I know this because of the size of the file.'

The size of the file?... Do you mean that you have the OBB and the APK on your device already downloaded directly from Google Play, but after starting the APK, you get a "download failed"?

**Comment by agamemnus** [comment]
Also -- does it all work when you are using a debug build?

**Comment by agamemnus** [comment]
As far as I can tell, everything looks fine in the code you linked...

**Comment by agamemnus** [comment]
Just updated 5.3.1. Made a bad copy earlier from the original instead of from my test version.
