### ISSUE TITLE
Improved configuration options

### ISSUE THREAD

**Issue by newjam** [agamemnus/cordova-plugin-xapkreader#29]
Hi! Thanks for your hard work on this plugin.

I was thinking it would be nice if this plugin could be configured more easily and in a more automated way.

[This plugin](https://github.com/01org/APKexpansion), which is doing something similar to yours, can be configured at install like this:

    cordova plugin add com.intel.xapkreader --variable MAIN_VERSION=1 --variable MAIN_FILESIZE=12345 --variable PATCH_VERSION=0 --variable PATCH_FILESIZE=0 --variable YOUR_PUBLICKEY="your own application publickkey" --variable DOWNLOAD_OPTION=true

I like this because I don't have to dig around in platform build files. I like being able to clean and rebuild the platforms directory easily.

I think better yet would being able to configure the plugin via the cordova projects `config.xml` like:

    <widget>
        ....
        <plugin name="cordova-plugin-xapkreader" version="2.3.4"/>
        <preference name="xapk_application_public_key" value="BLAH BLAH BLAH"/>
        <preference name="xapk_main_version" value="4"/>
    </widget>

I think this is the direction cordova is going with the 5.0.0+ releases.

**Comment by agamemnus** [comment]
The variable method at install is ok but the downside is that they aren't
optional afaik.

Using preference tags is definitely much cleaner than either of the other
methods. I think I will probably go with that.

Ideally what would be best is if we could have optional variables that we
can add at the time the plugin is added which turn into preference tag
parameters. Do you know if that's possible at all?

**Comment by newjam** [comment]
> Ideally what would be best is if we could have optional variables that we
> can add at the time the plugin is added which turn into preference tag
> parameters. Do you know if that's possible at all?

I think this is possible. I've never written a cordova plugin, but the crosswalk cordova plugin is doing this. Have a look at their [documentation for configuration](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview#configure) and the [code they use for configuring from both the command line during install, and the `config.xml` after install.](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/blob/master/hooks/update_config.js)

**Comment by agamemnus** [comment]
Oh yeah, they do a lot of funky stuff. Thanks for the links.

**Comment by agamemnus** [comment]
It's all doable because of gradle's flexibility, but it's going to take some time.

**Comment by newjam** [comment]
There was a cordova feature I didn't know about that solves this issue. When installing a plugin you can just add the `--save` flag to the end and it will save the plugin and the plugin variables to `config.xml`. Looks like we get this for free, already. Sorry for scaring you with the prospect of implementing this yourself :D.

**Comment by agamemnus** [comment]
Interesting. I will try this. Thumbs up!
