### ISSUE TITLE
Is this plugin compatible with Sqlite plugin?

### ISSUE THREAD

**Issue by ajenkul** [agamemnus/cordova-plugin-xapkreader#31]
I am wondering about my ionic project base on cordova. My app size is about ~200mb. Most of it are sqlite file. I use this plugin https://github.com/litehelpers/Cordova-sqlite-storage to read it. So, is this plugin support sqlite file?
P/S: I don't understand much in step `1` (how to zip an obb file), could you please explain it more clearly for me?
Thanks!

**Comment by agamemnus** [comment]
No idea. To zip it, use any zipping program. STORE means uncompressed. It's an option on most programs. I use the 7zip GUI for Windows and it works fine.
