### ISSUE TITLE
licensing issues

### ISSUE THREAD

**Issue by kimuraeiji214** [agamemnus/cordova-plugin-xapkreader#32]
I've fully read all the past issues and tried to reinstall this plugin several times but I'm still getting these issues.

<snip>

**Comment by kimuraeiji214** [comment]
> every
several

**Comment by agamemnus** [comment]
``cordova plugin add cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-5.3.1``
