### ISSUE TITLE
5.3.1, Error: more than one library with package name 'com.android.vending.expansion.downloader'

### ISSUE THREAD

**Issue by unskaa** [agamemnus/cordova-plugin-xapkreader#34]
After getting this error:
https://github.com/agamemnus/cordova-plugin-xapkreader/issues/33

I reinstalled the xapkreader with the 5.3.1 branch and got the error below. I'm fairly sure this problem is on my end but I have no idea how to solve it.

Error: more than one library with package name 'com.android.vending.expansion.downloader'
You can temporarily disable this error with android.enforceUniquePackageName=false
However, this is temporary and will be enforced in 1.0

**Comment by agamemnus** [comment]
(Please make sure to keep it to one issue thread. I'm not paid for this!)

I suggest that you uninstall the plugin and manually clear out anything that's left.

* ``platforms/android/`` should not have any ``com.flyingsoftgames.xapkreader`` or anything similar.
* Remove ``android/src/com/flyingsoftgames/xapkreader/``.
* Make sure project.properties does not have anything like this:
````
android.library.reference.3=com.flyingsoftgames.xapkreader/[your app name]-downloader_library
android.library.reference.4=com.flyingsoftgames.xapkreader/[your app name]-library
````
* Clear out android.json of anything related. Search for anything with "XAPKReader" in it (upper or lowercase).
* ``Remove res/values/xapkreader.xml``.
* Clear out ``com.flyingsoftgames.xapkreader`` from fetch.json. (maybe not that important but I don't know).

**Comment by CaptainCheerios** [comment]
I am having this same issue.  Its a fresh install of phonegap. 5.3.6 JDK 1.7, its a clean project and the only plugin added is this one, using the 5.3.1 instructions.

I have tried multiple times on multiple new projects.

**Comment by agamemnus** [comment]
Make a sample new project and post a link.

**Comment by unskaa** [comment]
I figured out what's causing this but I'm not sure how to fix this.

Let's assume my projects name is "mynewgame". On project.properties there would be:

target=android-22
android.library.reference.1=CordovaLib
cordova.gradle.include.1=cordova-plugin-crosswalk-webview/mynewgame-xwalk.gradle
android.library.reference.2=com.flyingsoftgames.xapkreader/mynewgame-downloader_library
android.library.reference.3=com.flyingsoftgames.xapkreader/mynewgame-library
android.library.reference.4=../../plugins/com.flyingsoftgames.xapkreader/android-sdk/extras/google/play_apk_expansion/downloader_library

If you remeve either the 2nd or the 4th reference, the build succeeds. Are one of those safe to be removed?

**Comment by agamemnus** [comment]
They are the essentially same, so yes.

You didn't add that last reference manually?

What Cordova and Android platform version are you on?

**Comment by unskaa** [comment]
I added the last one (reference.4) manually as the README tells me to. The "android.library.reference.2=com.flyingsoftgames.xapkreader/mynewgame-downloader_library" is added automatically when installing the plugin.

Which one should I remove?

cordova platform android version returns 4.1.1.
cordova -v returns 5.3.1

**Comment by agamemnus** [comment]
Thank you. Yes, the readme should have been updated. I am removing that now.
