### ISSUE TITLE
meta http-equiv="Content-Security-Policy" gives me an error

### ISSUE THREAD

**Issue by unskaa** [agamemnus/cordova-plugin-xapkreader#35]
On your README you list the following as one of the options to get "content://" working:

<meta http-equiv="Content-Security-Policy" content="* * 'self' default-src 'unsafe-inline' 'unsafe-eval' http://* https://* data: cdvfile://* content://*;">

When I view the console I receive the following error:
"Unrecognized Content-Security-Policy directive '*'."

This does not seem to harm the plugin in anyway. This is more like "just to let you know".

**Comment by agamemnus** [comment]
Thanks. I know. I'll look into it later...

**Comment by agamemnus** [comment]
Closing...
