### ISSUE TITLE
This plugin is not maintained anymore?

### ISSUE THREAD

**Issue by azizimusa** [agamemnus/cordova-plugin-xapkreader#37]
Is there any way i can get older files?

**Comment by agamemnus** [comment]
It is maintained. Check the readme.

**Comment by azizimusa** [comment]
i cant add the plugin, i follow exact command as in readme

**Comment by agamemnus** [comment]
Great. I guess you went to the 5.0 branch which I didn't update with specific branch instructions or a big warning.
