### ISSUE TITLE
Set iframe src to content:// url failing silently

### ISSUE THREAD

**Issue by thebarge** [agamemnus/cordova-plugin-xapkreader#38]
Hi,
I really appreciate this plugin -- it's made my life a lot easier! I do have one question/potential issue.

We have set up a simple app, and the premise works great -- we can load images from the expansion pack, etc. 

However, one of the key things we are trying to do is set an iframe's src to an html file that is in the expansion pack, and this is failing silently. Our initial assumption was that this was some type of security restriction, but we followed the instructions in the readme at https://github.com/agamemnus/cordova-plugin-xapkreader/blob/cordova-5.3.1/README.md. We are using your whitelist plugin.

We are setting the iframe's src using simple javascript: $("iframe")[0].src = "content://com.cloudkid.expansion/main_expansion/(path)/index.html".

We aren't seeing any output in any log, either using adb logcat or inspecting it via Chrome.

We have also tried with and without the crosswalk plugin, and it makes no difference.

We *can* get the contents of the html file in the expansion pack using jQuery.get("content://(path)/index.html") and verify that the html file exists.

Is this a known issue? We can create a simple version of our app with non-proprietary content if that would help diagnose things. Please let me know if you need more details. Thanks!

**Comment by agamemnus** [comment]
Shouldn't you have a . after the 0?

If it's not that, go ahead and make a sample project that I can run. I'll
check it out.

**Comment by thebarge** [comment]
Hi-
Yeah, that was just bad copy/pasting into the github issue. I made a slimmed-down project, attached as a zip. I have a theory that it has to do with the mime type of the assets, but that theory may be wrong. Thank you so much for any insight you have, I really appreciate it; I've been looking at this for a while now with no luck.


[expansionApp.zip](https://github.com/agamemnus/cordova-plugin-xapkreader/files/61473/expansionApp.zip)

**Comment by agamemnus** [comment]
Also, have you tried just removing the whitelist plugin altogether?

**Comment by agamemnus** [comment]
(I think some changes to the Cordova code might be needed, but I don't
remember..)

**Comment by thebarge** [comment]
Good idea - I tried removing the whitelist plugin, but no change.

**Comment by agamemnus** [comment]
And when you removed it, you also edited some other code to make that work? Last time I tried removing the whitelist plugin, it wouldn't compile.

**Comment by thebarge** [comment]
Yep, it compiled -- I did have to comment out a line in the `config.xml` -- `<plugin name="cordova-plugin-whitelist" spec="1" />` otherwise the build process would try to re-add the plugin.

**Comment by agamemnus** [comment]
Ok, I'll try the zip soon.

**Comment by thebarge** [comment]
Thank you so much, I really appreciate it. :smiley:

**Comment by agamemnus** [comment]
The local load is working correctly?

**Comment by agamemnus** [comment]
What happens when you don't use any parameters? ("?test") I think it is because it can't handle parameters.

**Comment by thebarge** [comment]
Hi, the url parameters don't matter, I should have stripped that out of my test. 

The local load works correctly for me - if you tap on the 'game 1' button you should see some text overlaid on top of the image. (The text is the content from www/assets/games/localGame/index.html.)

**Comment by thebarge** [comment]
Ha! I figured this out. My suspicion about the mime-type was correct -- to test in a hacky way, I switched the mime-type from `"vnd.android.cursor.item/asset"` to `"text/html"` in `XAPKProvider`, and commented out the mime-type check in `DownloadThread`. Doing that, I was able to see basic html, at least. Progress.

**Comment by agamemnus** [comment]
I wonder if there's an easy way to just make it use the correct mime-type... I will think about this, but let me know about your progress too, so I can integrate it.
