### ISSUE TITLE
Problem with source of <video> on Android

### ISSUE THREAD

**Issue by Atlan13** [agamemnus/cordova-plugin-xapkreader#41]
Hi there,

I have a project where I use many videos. So I have to outsource them to an expansion pack.
The normal uri for my videos are /android_assets/www/folder/video.mp4

Like in the tutorial https://iphonedevlog.wordpress.com/2014/12/12/adding-an-android-apk-expansion-file-to-a-cordova-project/ for images the uri content://de.examle.app/main_expansion/folder/image.jpg works perfectly.
But for videos the uri content://de.examle.app/main_expansion/folder/video.mp4 doesn't work. Has anybody an idea what is the solution of my problem?

Thank you for any advice!

**Comment by agamemnus** [comment]
Sounds familiar. What Cordova version?

**Comment by Atlan13** [comment]
Cordova version 5.4.0

**Comment by agamemnus** [comment]
Check: https://github.com/agamemnus/cordova-plugin-xapkreader/issues/38...

**Comment by Atlan13** [comment]
You mean that I have to do this:
"switched mime-type from "vnd.android.cursor.item/asset" to "text/html" in XAPKProvider, and commented out the mime-type check in DownloadThread"?
And the uri should stay like in the tutorial (content://...)?

**Comment by Atlan13** [comment]
I try this, but without luck. It works still perfectly for images, but videos could not be played.
Any additional ideas?

**Comment by agamemnus** [comment]
The mime-type should be one that is appropriate to your video format. I am
not sure what that is but it's not text/html. If even that doesn't work,
maybe you can change the video format and that could help?

**Comment by agamemnus** [comment]
No answer. OP possibly abducted by aliens. Closing.
