### ISSUE TITLE
Alpha test issue

### ISSUE THREAD

**Issue by piermariacosina** [agamemnus/cordova-plugin-xapkreader#42]
I've used the plugin successfully in local debug, I'm able to produce the debug apk create the folder and put the obb and everything work fine, but when I upload it in alpha test and install the app using the google play store, the app get stuck in the download screen with error download failed.

"download failed because you may not have purchased this app"

I've tried waiting the day after the upload but the issues is still there.

Also I've noticed that the app create the right folder in Android/obb/xxx folder and and inside there is already the obb, so I don't understand why there is a downloading screen in app

Is this  bug or a wrong configuration?

**Comment by agamemnus** [comment]
If it's a bug,  I've never seen something like this happen. Difficult to
say what is going on. Maybe it tried to download twice. Make sure you are
downloading a fresh copy and don't have your alpha there beforehand.

**Comment by piermariacosina** [comment]
when I download the app how much should be the weight of the download jist the apk or apk + obb?

**Comment by agamemnus** [comment]
Should be both I think but not sure anymore. Check my game "safari jigsaw"
for a comparison.

**Comment by piermariacosina** [comment]
with your app there isn't the same screen I see when I switch on the app, with the debug apk I don't see this screen only with the production one [http://postimg.org/image/ahs8xuilv/](url) (this one)

is it related to your plugin?

**Comment by agamemnus** [comment]
Yes, that is part of the plugin and indicates the download process is stuck
for some reason.

Just to clarify, you did delete your debug app before trying to download
your app again from the play store?

**Comment by piermariacosina** [comment]
Yes I've deleted multiple times, the debug version works like a charm the alpha test never... 
the app download immediately the obb so looks like that the app don't look for the right folder or obb file 

                      {
                            "xml": "<integer name=\"xapk_main_version\">0</integer>",
                            "count": 1
                        },
                        {
                            "xml": "<integer name=\"xapk_patch_version\">0</integer>",
                            "count": 1
                        },
                        {
                            "xml": "<integer name=\"xapk_main_file_size\">0</integer>",
                            "count": 1
                        },
                        {
                            "xml": "<integer name=\"xapk_patch_file_size\">0</integer>",
                            "count": 1
                        }
these information are mandatory or could be 0? in android.json

**Comment by agamemnus** [comment]
No, they are optional. If you are using Cordova 5.31, there shouldn't be
any problems. Perhaps your folder has spaces or characters that aren't
processed correctly. What is the folder name?

**Comment by piermariacosina** [comment]
it.enhancers.azimutyachts
main.107018.it.enhancers.azimutyachts.obb

the number in the file are generated by google play 

but in any case how could it be that in debug works and with alpha it is not?

**Comment by agamemnus** [comment]
Maybe you can try to find out what directory it is trying. Do you still get
the error you mentioned originally? ("download failed because you may not
have purchased this app")

**Comment by piermariacosina** [comment]
Solved, for some reason building the apk, it replaced the api key and replaced with your one that is setted by default, it was also similar to mine one so I didn't noticed this problem, now everything works fine. tnx for the help anyway :)

So there is no error or alert if the api key is wrong, non existent or from another domain

**Comment by agamemnus** [comment]
Ok, thanks. I'll see if I can do something about that on the next update.

**Comment by agamemnus** [comment]
Closing.
