### ISSUE TITLE
issue with this plugin

### ISSUE THREAD

**Issue by sirius2013** [agamemnus/cordova-plugin-xapkreader#43]
Hi,
I am very interesting this plugin.
I want to donate if you can help very small thing.

Are you available now?

**Comment by agamemnus** [comment]
Let me know what the issue is. I need to update it anyway...

**Comment by sirius2013** [comment]
It seems this doesn't support for sdk-23. android 6.0.

**Comment by sirius2013** [comment]
and I followed this
https://github.com/agamemnus/cordova-plugin-xapkreader/blob/cordova-5.3.1/test-project-instructions-and-test-obb/instructions.txt

but image didn't show on my app.

**Comment by sirius2013** [comment]
and please make sure how did you create obb file.
main.1.com.myproject.obb

**Comment by agamemnus** [comment]
Works in 6.5.0 now. I think. Closing.
