### ISSUE TITLE
Still can't solve library project name issue

### ISSUE THREAD

**Issue by vance** [agamemnus/cordova-plugin-xapkreader#45]
I sent a paypal donation =)

I read through all the posts on #22 and still don't quite understand how to fix this. Where project name is 'explore' I see the directory 'explore-library' next to the downloader library folder. Sorry, I don't understand gradle at all...

`Project with path ':com.flyingsoftgames.xapkreader:explore-library' could not be found in project ':com.flyingsoftgames.xapkreader:downloader_library'.`

I tried downgrading to cordova android@5.0.0 and with 6.1.1, both have the same error. 

I tried going up a level:

```
dependencies {
    debugCompile project(path: '..:com.flyingsoftgames.xapkreader:explore-library',configuration: "debug")
    releaseCompile project(path: '..:com.flyingsoftgames.xapkreader:explore-library',configuration: "release")
}
```

**Comment by agamemnus** [comment]
Why did you close this? I am really confused on all of this... everything keeps breaking. Just send me some breadcrumbs.

**Comment by agamemnus** [comment]
Did you manage to get it working on the fork?

**Comment by vance** [comment]
actually this worked as-is.. i did not have to modify this, i think i just confused myself by changing it.
