### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by webquali** [agamemnus/cordova-plugin-xapkreader#47]
When I install plugin I have empty android

I don't have added any plugins parameters.

Where problem?
[android.txt](https://github.com/agamemnus/cordova-plugin-xapkreader/files/392611/android.txt)

**Comment by agamemnus** [comment]
I don't understand. This isn't enough info to know the main problem.

**Comment by webquali** [comment]
Ok I try explain more.

I file readme for this plugin in section "#Completing Installation" writed:


4c) In android.json, look for and modify ``com.test.expansion`` and ``YOUR_GOOGLE_PLAY_LICENSE_KEY`` in this text:
`"res/values/xapkreader.xml": {
                "parents": {
                    "/*": [
                        {
                            "xml": "<string name=\"xapk_expansion_authority\">com.test.expansion</string>",
                            "count": 1
                        },
                        {
                            "xml": "<string name=\"xapk_google_play_public_key\">YOUR_GOOGLE_PLAY_LICENSE_KEY</string>",
                            "count": 1
                        }`


But when I do cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-5.3.1   I don't have in file "android.json" this text. More clerly?

**Comment by agamemnus** [comment]
Well, is this for 5.3.1?

**Comment by webquali** [comment]
yes for 5.3.1 and 5.0 the same problem

**Comment by agamemnus** [comment]
Idk. Should have worked. Try a new project?

**Comment by webquali** [comment]
I tried create new project have the same result.

cordova -v: 6.1.1
cordova platform ls: android 5.1.1

**Comment by agamemnus** [comment]
6.1.1 won't work!

**Comment by agamemnus** [comment]
I will try another effort to update this in a few days, including
contacting Google about it. Until Google updates the libraries, it will
constantly break.

**Comment by webquali** [comment]
Will be good. I will wait news from you.

**Comment by TarcisioYes** [comment]
Oh man, I can not wait for this plugin work in cordova 6.2.0. I could not find another solution for reading my expansion file (zip). Do you have any plans for that?

[sorry for my english]

**Comment by agamemnus** [comment]
Yes, sorry about the delay.

You can set up a caching system and have the user download your files from a CDN, after they download the base app.

**Comment by agamemnus** [comment]
Now works in 6+. Closing.
