### ISSUE TITLE
Error in Eclipse after integrate the plugin

### ISSUE THREAD

**Issue by chrisgip** [agamemnus/cordova-plugin-xapkreader#49]
First, thanks a lot for the job ! :)

I want to integrate this plugin because my app size 250 Mo.
So i followed the installation procedure but errors persist in Eclipse : 

![02-08-2016 17-47-33](https://cloud.githubusercontent.com/assets/20798147/17335269/ac9f6688-58d9-11e6-9a7f-6a9a2a61c8a7.png)

![02-08-2016 17-50-31](https://cloud.githubusercontent.com/assets/20798147/17335281/b51ec24a-58d9-11e6-89b4-971e27a1b55a.png)

Cordova version : 5.4.1

**Comment by agamemnus** [comment]
Eclipse is not supported. Maybe check again with latest version. Closing.
