### ISSUE TITLE
Build failed with exception afterinstalling cordova-plugin-xapkreader5.3.1

### ISSUE THREAD

**Issue by 4blocksinc** [agamemnus/cordova-plugin-xapkreader#52]
> D:\hell>cordova platform add android
> Adding android project...
> Creating Cordova project for the Android platform:
>         Path: platforms\android
>         Package: com.example.hell
>         Name: Hell
>         Activity: MainActivity
>         Android target: android-23
> Android project created with cordova-android@5.2.2
> Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
> Fetching plugin "cordova-plugin-whitelist@1" via npm
> Installing "cordova-plugin-whitelist" for android
>                This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do _not_ need this plugin since the whitelist will be built in.
> D:\hell>cordova platform add android
> Adding android project...
> Creating Cordova project for the Android platform:
>         Path: platforms\android
>         Package: com.example.hell
>         Name: Hell
>         Activity: MainActivity
>         Android target: android-23
> Android project created with cordova-android@5.2.2
> Installing "cordova-plugin-whitelist" for android
>                This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do _not_ need this plugin since the whitelist will be built in.
> D:\hell>cd platforms
> D:\hell\platforms>cd android
> D:\hell\platforms\android>cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader#cordova-5.3.1
> Fetching plugin "https://github.com/agamemnus/cordova-plugin-xapkreader" via git
>  clone
> Repository "https://github.com/agamemnus/cordova-plugin-xapkreader" checked out
> to git ref "cordova-5.3.1".
> Installing "com.flyingsoftgames.xapkreader" for android
> Notice: com.google.play.services has been automatically converted to cordova-google-play-services and fetched from npm. This is due to our old plugins registry shutting down.
> Fetching plugin "cordova-google-play-services" via npm
> Installing "cordova-google-play-services" for android
>  See the README.md file to complete your installation.
> D:\hell\platforms\android>cordova build android
> ANDROID_HOME=C:\Users\Ruben\AppData\Local\Android\sdk
> JAVA_HOME=C:\Program Files\Java\jdk1.8.0_31
> Incremental java compilation is an incubating feature.
> FAILURE: Build failed with an exception.
> - Where:
>   Script 'D:\hell\platforms\android\com.flyingsoftgames.xapkreader\hell-downloader_library\build-extras.gradle' line: 2
> - What went wrong:
>   A problem occurred evaluating script.
>   
>   > Project with path ':com.flyingsoftgames.xapkreader:hell-library' could not be found in project ':com.flyingsoftgames.xapkreader:downloader_library'.
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 5.604 secs
> Error: cmd: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> - Where:
>   Script 'D:\hell\platforms\android\com.flyingsoftgames.xapkreader\hell-downloader
>   _library\build-extras.gradle' line: 2
> - What went wrong:
>   A problem occurred evaluating script.
>   
>   > Project with path ':com.flyingsoftgames.xapkreader:hell-library' could not be found in project ':com.flyingsoftgames.xapkreader:downloader_library'.
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by 4blocksinc** [comment]
Any one can help us here

**Comment by agamemnus** [comment]
I am not sure you are using 5.3.1.

**Comment by 4blocksinc** [comment]
i have install 5.3.1

**Comment by agamemnus** [comment]
"Android project created with cordova-android@5.2.2". Does this match with Cordova 5.3.1? I am not positive here.

Try making without a whitelist?

**Comment by 4blocksinc** [comment]
can you we do a 10min teamviewer so that we can resolve this please

**Comment by agamemnus** [comment]
Okay. Fine.

**Comment by agamemnus** [comment]
Just email me...

**Comment by 4blocksinc** [comment]
your email id please

**Comment by 4blocksinc** [comment]
or just tell me the steps i will follow

**Comment by agamemnus** [comment]
It is the same as my username, with a gmail at the end.

**Comment by 4blocksinc** [comment]
Thanks for the time bro!
