### ISSUE TITLE
Import package org.apache.http does not exist

### ISSUE THREAD

**Issue by sallison117** [agamemnus/cordova-plugin-xapkreader#55]
/Users/sethallison/Projects/GuardianWindowInsight_android_exp/InsightApp/climaguardapp_final/platforms/android/com.flyingsoftgames.xapkreader/climaguardglass-library/src/com/google/android/vending/licensing/APKExpansionPolicy.java
Error:(20, 23) error: package org.apache.http does not exist
Error:(21, 36) error: package org.apache.http.client.utils does not exist
same in 
/Users/sethallison/Projects/GuardianWindowInsight_android_exp/InsightApp/climaguardapp_final/platforms/android/com.flyingsoftgames.xapkreader/climaguardglass-library/src/com/google/android/vending/licensing/ServerManagedPolicy.java

Tried these http://stackoverflow.com/questions/31433687/android-gradle-apache-httpclient-does-not-exist, most articles are around this line but it does not work.

**Comment by agamemnus** [comment]
Only works for 5.3.1.

**Comment by sallison117** [comment]
Overall Cordova or Android platform sorry don't work with Cordova much.

**Comment by agamemnus** [comment]
Cordova.

**Comment by sallison117** [comment]
Now I get this error when trying to install a plugin. I not sure if this an addition bug or ralted but I reduced my cordova version to 5.3.1.
Fetching plugin "com.google.play.services" via npm
WARNING: com.google.play.services has been renamed to cordova-google-play-services. You may not be getting the latest version! We suggest you `cordova plugin rm com.google.play.services` and `cordova plugin add cordova-google-play-services`.
Fetching plugin "com.google.play.services" via cordova plugins registry
Failed to install 'com.flyingsoftgames.xapkreader':CordovaError: Failed to fetch plugin com.google.play.services via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: connect ETIMEDOUT 50.17.177.14:80
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:141:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Failed to fetch plugin com.google.play.services via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: connect ETIMEDOUT 50.17.177.14:80

**Comment by agamemnus** [comment]
It's not a bug. New naming doesn't work right with 5.3.1. You probably left
something there when you switched to 5.3.1.
