### ISSUE TITLE
org.apache.http

### ISSUE THREAD

**Issue by webplease** [agamemnus/cordova-plugin-xapkreader#57]
Error compiling ...why ?

Error:(20, 23) error: package org.apache.http does not exist
Error:(21, 36) error: package org.apache.http.client.utils does not exist
Error:(382, 18) error: cannot find symbol class NameValuePair
Error:(382, 45) error: cannot find symbol variable URLEncodedUtils
Error:(383, 18) error: cannot find symbol class NameValuePair

**Comment by agamemnus** [comment]
Stale comment. Closing.
