### ISSUE TITLE
visual studio cant load project after adding plugin

### ISSUE THREAD

**Issue by Slim2k** [agamemnus/cordova-plugin-xapkreader#60]
I have installed the plugin using the following Cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-5.3.1

Now visual studio won't load the solution and just crashes out, has anyone else had this issue?

**Comment by agamemnus** [comment]
It's probably an issue with npm recently being unable to find the Google
play library in the form the plugin wants it, but who knows.

**Comment by Slim2k** [comment]
Can you advise of a manual way of getting around this?

**Comment by Slim2k** [comment]
Any suggestions on how to fix this?

**Comment by agamemnus** [comment]
You might want to use the new 6+ version mentioned in the last few issues.

I guess I'll have to update since it seems to all work well now.

**Comment by Slim2k** [comment]
Sorry, can you elaborate?

I should update to cordova 6+, my app is curreltny running stable on v 5.4.1.

Can you confirm what you need to update and why?

Thank you

**Comment by agamemnus** [comment]
Issue 58 and 59!

**Comment by Slim2k** [comment]
So I need to update the app to use cordova 6.3.0 and pull https://github.com/agwells/cordova-plugin-xapkreader/commits/cordova-6.3

Will this resolve the issue of it getting the google play services libs or do I need to do something else for that?

**Comment by agamemnus** [comment]
Yes, since it uses a different text.

**Comment by agamemnus** [comment]
I mean a different way to access the lib.

**Comment by Slim2k** [comment]
Thanks, it seems to have sorted itself. But I still cannot access the files.

**Comment by agamemnus** [comment]
Idk.

**Comment by Slim2k** [comment]
So that all looks correct to you?, I appreciate you haven't seen the complete solution, but their the core references that you specify in the documentation.

I have hit a brick wall with this one, been on it since 8:30am this morning (GMT) and still cant get it working! :(

**Comment by agamemnus** [comment]
Try a file other than mp4. Make sure your whitelist plugin isn't
interfering...

**Comment by Slim2k** [comment]
Cheers, it was a whitelist issue, which sorted it for both .png and .mp4

Mine  -  `<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src * 'unsafe-inline' 'unsafe-eval' http://* https://* data: cdvfile://* content://*; img-src 'self'">">`

yours -  `<meta http-equiv="Content-Security-Policy" content="* * 'self' default-src 'unsafe-inline' 'unsafe-eval' http://* https://* data: cdvfile://* content://*;">`

Thanks for your help and a great plugin.
