### ISSUE TITLE
content not ready immediately after download on Android 6

### ISSUE THREAD

**Issue by fabrizio-leonardi** [agamemnus/cordova-plugin-xapkreader#61]
We are using this plugin in our Ionic project to load assets from an expansion obb file.
In Android 6 contents are not immediatly available after the download process and requiring a resource with content://package/main_expansion/img/image.png gives a 404 
in logcat: AndroidProtocolHandler: Unable to open content URL: content://package/main_expansion/img/image.png
It works fine if we wait some time before requiring image.png (or closing and starting again the application)

**Comment by agamemnus** [comment]
Maybe there is an event you can capture, but what it is, I don't know.

**Comment by agamemnus** [comment]
Possibly fixed per https://github.com/agamemnus/cordova-plugin-xapkreader/pull/64.
