### ISSUE TITLE
Version Problem

### ISSUE THREAD

**Issue by phengsengvuthy** [agamemnus/cordova-plugin-xapkreader#62]
Hello Dear,

Many people have problems with Cordova version. This plugin support version 5-3-1, for now Cordova version is 6++. Please valued dear update this plugin. :-D

Sincerely,
Pheng Sengvuthy

**Comment by agamemnus** [comment]
If you look at the issues list there are people who have developed newer
versions. I never get around to it. I guess I will make a commitment to do
this by next month..., but you can look around for a solution there
meanwhile.

**Comment by agamemnus** [comment]
Cordova 5.3.1-auto should work with latest 6.5.0 version. I duplicated it to the 6.5.0 branch as well.

**Comment by phengsengvuthy** [comment]
Hello Dear could take a video toturial about this plugin for you users ?

Many problems dear.

**Comment by agamemnus** [comment]
I don't know what I would say.

What problems are you experiencing? Are you using the latest Android & Cordova?

**Comment by phengsengvuthy** [comment]
I got many errors in android project dear.

**Comment by phengsengvuthy** [comment]
Hello,

How to get image path in typescript ? PLEASE

**Comment by agamemnus** [comment]
Do it in JavaScript first and see what happens. I don't use Typescript so I
can't help.
