### ISSUE TITLE
:com.flyingsoftgames.xapkreader:library' could not be found

### ISSUE THREAD

**Issue by BobAchgill** [agamemnus/cordova-plugin-xapkreader#68]
Any idea as to why 6.5.0 would Build Failed like this??

```
FAILURE: Build failed with an exception.

* Where:
Script 'F:\CORDOVA_WORKING\et-ethiopia-eth-amh-fra\platforms\android\com.flyings
oftgames.xapkreader\hellocordova-downloader_library\build-extras.gradle' line: 2


* What went wrong:
A problem occurred evaluating script.
> Project with path ':com.flyingsoftgames.xapkreader:library' could not be found
 in project ':com.flyingsoftgames.xapkreader:hellocordova-downloader_library'.

BUILD FAILED
```

**Comment by agamemnus** [comment]
Make sure you have everything updated to the latest version.

Try on F:\test and C:\test.. (humor me).

**Comment by BobAchgill** [comment]
Like this??


```
C:\et-ethiopia-eth-amh-fra>cordova -v
6.5.0

C:\et-ethiopia-eth-amh-fra>npm -v
3.10.10

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

C:\et-ethiopia-eth-amh-fra>cordova build android
Discovered plugin "cordova-plugin-tag-manager" in config.xml. Adding it to the p
roject
Fetching plugin "cordova-plugin-tag-manager@~1.0.1" via npm
Installing "com.jareddickson.cordova.tag-manager" for android
ANDROID_HOME=C:\Users\Ownerc\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_111
Subproject Path: CordovaLib
Subproject Path: com.flyingsoftgames.xapkreader/hellocordova-downloader_library
Subproject Path: com.flyingsoftgames.xapkreader/hellocordova-library
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\et-ethiopia-eth-amh-fra\platforms\android\com.flyingsoftgames.xapkrea
der\hellocordova-downloader_library\build-extras.gradle' line: 2

* What went wrong:
BUILD FAILED

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by agamemnus** [comment]
Try a clean build on C:\test and don't add other plugins.

**Comment by agamemnus** [comment]
Please try https://github.com/agamemnus/cordova-plugin-xapkreader/issues/66#issuecomment-284737448.

**Comment by BobAchgill** [comment]
Three questions:
1) Do both the obb folder need to have .expansion in the name
e.g. 
android/obb/org.hishandsreader.cameroon_cm1_fra_spa.expansion/main.10.org.hishandsreader.cameroon_cm1_fra_spa.expansion.obb

2) Is the directory structure in the obb file using the www directory as the root?

3) Will the plugin not work if there is only a dummy licence key?  The reason I ask is because I hope to use the plugin in cases where Google Play store is not used for distribution.
e.g.
--variable XAPK_PUBLIC_KEY="your_google_play_license_key"

**Comment by agamemnus** [comment]
1) No need to use that anywhere actually.

2) I don't remember.

3) The plugin is designed to work with the Google play store. The public key is part of the download process. So you'd probably need to make a bunch of modifications to use it the same way without the Google play store....

**Comment by BobAchgill** [comment]
I need to distribute a 1+GB app via extSD in developing countries that is used for learning to read their mother tongue.  Hence the need for a feature in cordova-plugin-xapkreader that has the option to not force the use the of a google_play_license_key.  This way the app can be passed on cheap SDcards where no internet is available or too expensive to use.  In this scenario the ... `android/obb/org.literacy.app.expansion/main.10.org.literacy.app.expansion.obb`  AND  install apk are preinstalled on the SD.  The user just inserts the SD installs the APK and the literacy app accesses the 1GB of literacy media on the same extSD.  Is that possible with cordova-plugin-xapkreader?

**Comment by agamemnus** [comment]
Not without a lot of modifications.

Why don't you simply access the files using the file system? Cordova has built-in file access methods.

**Comment by BobAchgill** [comment]
I entered a draft of the application for my app with Google Play Console.  It let me copy the license key.  Can I manually put the obb file in place and test the cordova compile against the obb file using that license key... or do i have to complete the application ... upload the apk ... get approval from Google for the app before I can test the compile??  The reason I am asking is because manually putting the obb file on the ExtSD and testing is achieving results of the media being found in the obb file.

**Comment by agamemnus** [comment]
The license key is needed for being able to download the obb file from Google's servers. _I don't think you need the app published for the license key to work.) But since in your case people are not downloading the app from Google, it shouldn't be a concern...

So I guess theoretically you're just using a subset of the plugin which  basically deals with unzipping a big file and putting the contents inside a virtual directory.

I guess it should work in debug mode without even a valid license key, but I'm not sure it will work without Google play present (doesn't have to be set up), for example.

**Comment by BobAchgill** [comment]
I got the app to compile with no errors but I get this error when exercising a media link to a file that is located in the obb expansion file...

```
Application Error
There was a network error.
(content://org.hishandsreader.cameroon-cm1-fra-spa.expansion/adventure.mp4)
```


Here is the procedure I followed to do the test...


Steps to compile a Cordova project using agamemnus/cordova-plugin-xapkreader

1) Create a clean project
```
C:\> cordova create cm-cameroon_cm1_fra_spa
C:\> cd cordova create cm-cameroon_cm1_fra_spa
```

2) Modify the config.xml

`config.xml`

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="org.hishandsreader.cameroon_cm1_fra_spa" version="0.0.1" android-versionCode="10" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    
<name>HHR cm-cm1-fra-spa</name>
    
<description>
      Mother tongue literacy videos for: cameroon-cm1-fra-spa
  </description>
    
<author email="MyEmail@HisHandsReader.org" href="http://www.HisHandsReader.org">
      Robert Achgill
  </author>
    
<content src="index.html" />
    
<plugin name="cordova-plugin-whitelist" />

	


<!-- needed for GooglePlay expansion file -->
    
<allow-navigation href="*://*/*"/>
    
<allow-intent href="*" />
    
<access origin="*" />
    
<access origin="content:///*" />
    
<access origin="cdvfile:///*" />
	
    
<platform name="android">
        
<allow-intent href="market:*" />
		  
 <preference name="android-installLocation" value="auto" />
    
</platform>


</widget>
```

3) Modify the index.html

`index.html`

```
<!DOCTYPE html>
<html>
    <head>
        <!-- Put in this meta tag -->
        <meta http-equiv="Content-Security-Policy" content="* * 'self' default-src 'unsafe-inline' 'unsafe-eval' http://* https://* data: cdvfile://* content://*;">

        <title>Hello World</title>
    </head>
    <body>
<!-- Point to some sample media file that is stored on the extSD obb expansion file that you store on the extSD of the phone -->
<!-- Add the extension '.expansion' to make the Expansion Authority link as author says this will help prevent collisions with other places in the code. --> 
	
   <p><a href="content://org.hishandsreader.cameroon-cm1-fra-spa.expansion/video/adventure.mp4">adventure </a></p>
  
    </body>
</html>
```

4) Add android platform

`C:\cm-cameroon_cm1_fra_spa>  cordova platform add android@latest`

5) Get Googlle Play license key by creating an app on the Google Play Developer Console

6) Add the xapkreader plugin using the two variables.  See note in step 3 about adding '.expansion' to create the exp auth link... see note 5 about where to get the Google Play license key.   Author says you can use the key before the apk is uploaded and approved by Google.... to do manual testing of the obb file access.

`C:\cm-cameroon_cm1_fra_spa>  cordova plugin add https://github.com/agamemnus/cordova-plugin-xapkreader.git#cordova-6.5.0 --variable XAPK_EXPANSION_AUTHORITY="org.hishandsreader.cameroon_cm1_fra_spa.expansion" --variable XAPK_PUBLIC_KEY="your_google_play_license_key"`

7) Do a build

`C:\cm-cameroon_cm1_fra_spa>  cordova build android `

8) make obb file for GooglePlay expansion file using 7zip command line.  Execute this line in the directory where your media directory structure exists.  
 
 `C:\zipworking>  7z a archive.zip -mx0`

      where `C:\zipworking/video/adventure.mp4`

       The contents of archive.zip now contains the subdirectory video with the uncompressed adventure.mp4 in it.

9)  rename  archive.zip to the obb expansion file name...
` main.10.org.hishandsreader.cameroon_cm1_fra_spa.obb`

10) Manually store the obb expansion file on the phone extSD for testing to see if the link in the index.html can access the media file.
`<shared-storage>/Android/obb/<package-name>/<obb file name`
e.g.
`/Android/obb/org.hishandsreader.cameroon_cm1_fra_spa.expansion/main.10.org.hishandsreader.cameroon_cm1_fra_spa.obb`

**Comment by agamemnus** [comment]
If you're using the Media plugin to run the video, it won't work. You'd need to use crosswalk.

Are you testing with an emulator? Also a problem...

**Comment by BobAchgill** [comment]
Not sure why but I have not had to use Media plugin to play media in my Android cordova apps.  So  NO.  I am not using it.

I am testing using a Galaxy S7.

I wonder if this is just a path issue.  The error says...
`(content://org.hishandsreader.cameroon-cm1-fra-spa.expansion/adventure.mp4)`
Maybe, I am supposed to put the version number in either the obb folder name or the expansion authority link name??  They had me put it in the obb file name... so just wondering.

**Comment by agamemnus** [comment]
No, you do not need the version number anywhere. Not even in the obb filename. The app automatically detects filenames in the directory.

Test for instances where things seem to work. Static files? Other videos? Images? Audio?

**Comment by cquezpro** [comment]
I can help you.

**Comment by cquezpro** [comment]
hello!

Are you really working for this?

or just send message " Not yet..."?

**Comment by BobAchgill** [comment]
Had a similar error with cordova.plugins.diagnostic not finding the path to the extSD.  It turned out that I needed to add a run time permission because my Android device is 6.0 or above.  Does cordova-plugin-xapkreader have a run time persmission function I can try?


> https://github.com/dpa99c/cordova-diagnostic-plugin-android-runtime-example
> Android runtime permissions
> 
> Android 6 / API 23 introduces the concept of runtime permissions. Similar to iOS, certain "dangerous" permissions must be requested at runtime in addition to being listed in the Android manifest.
> 
> Runtime permissions only apply if the device/emulator the app is running on has Android 6.0 or above AND the app is built using API 23 or higher. For Cordova, this means using the Cordova Android platform version 5.0.0 or above. If the app is built with version 4.x or below (API 22 or below), runtime permissions do not apply - all permissions are granted at installation time.

**Comment by agamemnus** [comment]
Well, no. This was developed way before that. Maybe you just need a
different (updated) SDK...

Check out issue #94.

**Comment by eric80** [comment]
Yes, it works fine

**Comment by BobAchgill** [comment]
So what android api should be the target for this plugin?  Something less than 23 to avoid the run time permissions issue.  What is too low of a target?

**Comment by agamemnus** [comment]
Come to issue #94.

**Comment by BobAchgill** [comment]
I get the error...
```
Application Error
There was a network error. (content://org.hishandsreader.cameroon-cm1-fra-spa.expansion/0011_adventure1.mp4)
```
I am using platform Android 5.1.1
And my phone is Android 7

**Comment by BobAchgill** [comment]
Can you post a simple working obb example project on git?

**Comment by agamemnus** [comment]
I did post the steps... might be slightly outdated.

Can you try a different file? A text file perhaps.
