### ISSUE TITLE
Cannot get file path from OBB file

### ISSUE THREAD

**Issue by phengsengvuthy** [agamemnus/cordova-plugin-xapkreader#75]
I tried to get file path from OBB, but I got many errors in Android Studio !

<img width="1223" alt="screen shot 2017-03-15 at 6 24 37 pm" src="https://cloud.githubusercontent.com/assets/16508039/23946374/bbe26fc6-09ac-11e7-9bef-ffef866a3163.png">

**Comment by agamemnus** [comment]
Android Studio is not supported, because I don't know/use it.

**Comment by agamemnus** [comment]
Please make sure to use the latest 6.5 (it was updated less than a day ago), and take care that your OBB zip file is a STORE (uncompressed).

**Comment by agwells** [comment]
If your filename has a space or other url-encodable character in it, it could be this issue (fix now merged into the 6.5 branch): https://github.com/agamemnus/cordova-plugin-xapkreader/pull/69
