### ISSUE TITLE
Can't read content of obb file when obb file is big

### ISSUE THREAD

**Issue by cquezpro** [agamemnus/cordova-plugin-xapkreader#76]

**Comment by agamemnus** [comment]
No one has yet encountered such an issue to my knowledge.

You're absolutely sure that it is a store? Are you sure it is a file size
issue? Try to check this rigorously by using different sized file and
figure out at exactly what size it breaks. This might provide a basis for a
search to narrow down the issue.

NB: You can test all this with a development build. No need to keep
uploading to Google...

**Comment by sirius2013** [comment]
yes, it worked fine when size was 500MB,
but I added several folders/files around 100MB.
and tried to read same file. but got not found error.
![image](https://cloud.githubusercontent.com/assets/5020713/24008053/6afd8848-0aab-11e7-97bc-b8cd0fcf8ffb.png)

**Comment by agamemnus** [comment]
I suggest you start removing until you get to that one size or maybe file
which causes the problem.

If it is a file size problem it is probably somewhere in Google's library
code... Maybe.

**Comment by sirius2013** [comment]
okay, thanks

**Comment by sirius2013** [comment]
Hi
I debugged android, and found out the issue at XAPKZipResourceFile.java
 public void addPatchFile (String zipFileName) throws IOException function.

numEntries is minus value.

**Comment by sirius2013** [comment]
I am not sure how can I fix for that.

**Comment by sirius2013** [comment]
numEntries = -31626

**Comment by sirius2013** [comment]
![image](https://cloud.githubusercontent.com/assets/5020713/24058825/8cd2b146-0b87-11e7-8ad4-c5231cc2f6d9.png)

**Comment by agamemnus** [comment]
Ok, checking.

**Comment by sirius2013** [comment]
Thanks
int numEntries = bbuf.getShort(eocdIdx + kEOCDNumEntries);
eocdIdx = 65535, kEOCDNumEntries =8
but numEntries = -31626

**Comment by agamemnus** [comment]
Try making the following change, then re-compile. Change:
`int numEntries = bbuf.getShort(eocdIdx + kEOCDNumEntries);`
...to:
`int numEntries = bbuf.getInt(eocdIdx + kEOCDNumEntries);`

Let me know how that works asap!

**Comment by sirius2013** [comment]
same error.
now numEntries = -2072607626

**Comment by agamemnus** [comment]
How many files/directories do you have?

**Comment by sirius2013** [comment]
files: 45554, folders: 2789

**Comment by agamemnus** [comment]
Try `bbuf.getInt(eocdIdx + kEOCDNumEntries) & 0xffffffffL;`. Also, let's output the data:
`Log.v (LOG_TAG, eocdIdx + " " + kEOCDNumEntries);`.

**Comment by sirius2013** [comment]
app crashed. :(
java.lang.IndexOutOfBoundsException: index=4514771, limit=4514771, size of type=4
03-17 15:29:56.268 14073-14118/com.flinklearning.marshalladult W/System.err:     at java.nio.Buffer.checkIndex(Buffer.java:165)

**Comment by agamemnus** [comment]
I'm stumped. No log data?

**Comment by sirius2013** [comment]
65535 8

**Comment by sirius2013** [comment]
eocdIdx=65535 kEOCDNumEntries=8

**Comment by agamemnus** [comment]
Go ahead and change LOGV to true. on line 43.. I want to see if there is anything else.

**Comment by sirius2013** [comment]
V/zipro: +++ Found EOCD at index: 65535.
03-17 15:40:57.648 17572-17692/com.flinklearning.marshalladult V/zipro: 65535 8

**Comment by sirius2013** [comment]
V/zipro: +++ numEntries=2222359670 dirSize=4514771 dirOffset=1070617189

**Comment by agamemnus** [comment]
Huh. Go ahead and make it a long?
`long numEntries = bbuf.getInt(eocdIdx + kEOCDNumEntries)  & 0xffffffffL;`

**Comment by sirius2013** [comment]
yes, tried that.

**Comment by agamemnus** [comment]
I just don't think this code was designed for so many files. I think that is the problem. Can you get a trace on the error -- what line number in XAPKZipResource.java sets it off?

**Comment by sirius2013** [comment]
I think you can check on your end with many files and folders.

**Comment by agamemnus** [comment]
You did the same thing with the screenshot earlier... just get that same thing so we can see what line it is coming from now...

**Comment by sirius2013** [comment]
I am not super with this, so can't figure out this myself. so need help for this.
and I confirmed this is files/folders count problem instead of obb file size.
it worked with 2GB (less files/folders) obb file.

**Comment by agamemnus** [comment]
Can you generate such an obb ---with as small a file size as possible --
and link it. I will then play with it tomorrow.

**Comment by sirius2013** [comment]
hello. :) can you download from google drive  link?

**Comment by sirius2013** [comment]
file size is around 1.6GB

**Comment by agamemnus** [comment]
Maker it smaller please!

**Comment by sirius2013** [comment]
sorry, no idea how to make smaller with many files and folders.
anyway here it is.
https://drive.google.com/open?id=0BxZueVVvaQcBM05NdFA4eHMyZ2s

**Comment by agamemnus** [comment]
Just generate some small files for me please!!

**Comment by sirius2013** [comment]
any good news?

**Comment by agamemnus** [comment]
Make me small files. I can't really work on this until it is very very
small...

**Comment by sirius2013** [comment]
hmm, we have issue with big size/many files/folders. I need help for fixing that.

**Comment by agamemnus** [comment]
It's just the number of files, isn't it? Or is it a combination?

**Comment by sirius2013** [comment]
I think both.

**Comment by agamemnus** [comment]
Please just try creating a bunch of dummy files with minimal file sizes to
check.

**Comment by sirius2013** [comment]
sorry, I can't

**Comment by agamemnus** [comment]
Why not man?

**Comment by agamemnus** [comment]
I'm too lazy to do it. I have a lot of other things I need to do... So
maybe I will do that but, later.

**Comment by sirius2013** [comment]
I am not data entry man.

**Comment by agamemnus** [comment]
You can programmatically make the files. Or wait.

**Comment by agamemnus** [comment]
Hey,

Maybe there is some way you can reduce the number of files? If you describe the files and your app, maybe I can give you a few possibilities.

For example, maybe some of the files are related -- you can then use HTML5's canvas to take the image and split it into pieces.

**Comment by sirius2013** [comment]
any good news?
The number of files and folders is directly related to the size of the obb.
so please try above file.

**Comment by sirius2013** [comment]
here it is again.
https://drive.google.com/open?id=0BxZueVVvaQcBM05NdFA4eHMyZ2s

**Comment by sirius2013** [comment]
here is small size zip file, but many files and folders.
https://drive.google.com/open?id=0BxZueVVvaQcBTEpJMmpTZTdfdm8

**Comment by sirius2013** [comment]
Please work with this and let me know when you fix this. thanks

**Comment by agamemnus** [comment]
Thanks. I'll take a look in a bit but I might not be able to fix it.

U suggest you think of ways to use fewer files in free meantime.

By the way, there's no team. There's just me, and it's a volunteer effort.

**Comment by sirius2013** [comment]
If you fix this issue shortly, you will be get paid for this.

**Comment by sirius2013** [comment]
hello, any good news?

**Comment by agamemnus** [comment]
Sorry, might take a while. No guarantees.

**Comment by sirius2013** [comment]
hi, any good news?
thanks

**Comment by sirius2013** [comment]
any good news?
I want to pay you for this issue.
please let me know. thanks
very urgent really.

**Comment by agamemnus** [comment]
I will try in a couple of days but it's not likely I can fix this. You
should really see if you can redesign the app.

On Mar 22, 2017 1:18 PM, "MobileWebPro" <notifications@github.com> wrote:

any good news?
I want to pay you for this issue.
please let me know. thanks
very urgent really.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/agamemnus/cordova-plugin-xapkreader/issues/76#issuecomment-288473046>,
or mute the thread

**Comment by agamemnus** [comment]
What is your email address?

On Mar 22, 2017 1:42 PM, "Michael Romanovsky" <agamemnus@gmail.com> wrote:

I will try in a couple of days but it's not likely I can fix this. You
should really see if you can redesign the app.

On Mar 22, 2017 1:18 PM, "MobileWebPro" <notifications@github.com> wrote:

any good news?
I want to pay you for this issue.
please let me know. thanks
very urgent really.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/agamemnus/cordova-plugin-xapkreader/issues/76#issuecomment-288473046>,
or mute the thread

**Comment by sirius2013** [comment]
betopone1021@gmail.com

**Comment by sirius2013** [comment]
hello?

**Comment by agamemnus** [comment]
Not yet!!! I'll contact you tomorrow EST.

**Comment by sirius2013** [comment]
any update? one week is passed!

**Comment by sirius2013** [comment]
this is fixed?

**Comment by sirius2013** [comment]
hello, any good news?

**Comment by sirius2013** [comment]
Btw what do you think what is maximum number of file issue?

Thanks

**Comment by sirius2013** [comment]
hello!

Are you really working for this?

or just send message " Not yet..."?
