### ISSUE TITLE
Content MIME Type setting?

### ISSUE THREAD

**Issue by probt** [agamemnus/cordova-plugin-xapkreader#79]
Thank you for the plugin; it's very easy to add and set up.  I am running into a similar issue to #38; if I link to an SVG file, it won't display since the content type is being set as "vnd.android.cursor.item/asset" (it should be "image/svg+xml").  Is it possible to read the MIME type from the expansion file?  I couldn't find where exactly that information was being saved/referenced. The issue also occurs for HTML and CSS files.

**Comment by agamemnus** [comment]
Ok, I did a quick search and I found `Files.probeContentType(path)` from http://stackoverflow.com/questions/51438/getting-a-files-mime-type-in-java. Try modifying `@Override public String getType (Uri uri) {return "vnd.android.cursor.item/asset";}` on line 71 in `src/android/XAPKProvider.java` and see if that works. If it does, I will edit...

**Comment by probt** [comment]
Thanks for the speedy reply; I think implementing that may be beyond my skill level, but I'll give it a try.

**Comment by agamemnus** [comment]
It's just:
``@Override public String getType (Uri uri) {return Files.probeContentType(uri);}``

Plus add it to the top (line 19) per https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html:
`import java.nio.file.Files;`

**Comment by probt** [comment]
It appears java.nio.file is not available on Android (although it looks like it has been added to Android O).  Could android.webkit.MimeTypeMap being used as an alternative?

**Comment by agamemnus** [comment]
No idea. Just try.

**Comment by agamemnus** [comment]
Just try.

**Comment by chipbell4** [comment]
We resolved this by using `URLConnection.guessContentTypeFromName(uri.toString ())`, as can be seen [here](https://github.com/SpringRoll/cordova-plugin-xapkreader/blob/cordova-5.3.1/src/android/XAPKProvider.java#L71) which seems to work for the asset types we've needed.

**Comment by chipbell4** [comment]
Also, I can make a PR back to both the 5.3.1 and 6.5.0 branches if you'd like, but it's a pretty small change and may be easier for you to do it. Let me know how I can help!

**Comment by agamemnus** [comment]
It would be easier if you did it for both. Thanks.

**Comment by agamemnus** [comment]
Hold on a sec. I actually don't use that function anymore.

**Comment by agamemnus** [comment]
Or maybe I do. Just hold on..

**Comment by agamemnus** [comment]
I thought I reworked the whole thing. I seem to recall.... But ok. Maybe not. Too much black box stuff. Ok, go ahead.

**Comment by chipbell4** [comment]
@paulrbt I think this should be resolved as of #109 and #110 . If you have a moment, take a look and let me know.
