### ISSUE TITLE
audio is not working in obb

### ISSUE THREAD

**Issue by cquezpro** [agamemnus/cordova-plugin-xapkreader#80]
Hi,

I tried to play an audio file from an .obb, but it didn't work.

**Comment by agamemnus** [comment]
https://github.com/agamemnus/cordova-plugin-xapkreader/blob/cordova-6.5.0/media_plugin_workaround.txt

This is all I can suggest.

**Comment by cquezpro** [comment]
okay, thanks

**Comment by sirius2013** [comment]
hello, any good news?

**Comment by sirius2013** [comment]
Btw what do you think what is maximum number of file issue?

Thanks

**Comment by cquezpro** [comment]
hello!

Are you really working for this?

or just send message " Not yet..."?
