### ISSUE TITLE
net::ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by roedoejet** [agamemnus/cordova-plugin-xapkreader#98]
Hi there,

Looking for some help debugging an issue with the plugin. I've added the plugin to my project as described for cordova 6.5 but the content:// URL scheme is still not recognized. My obb is a stored zip with one folder called "audio". 

`content://com.firstvoices.lilwat_fphlcc/audio/183Sounds20060713173801859seal_lil.mp3:1 GET content://com.firstvoices.lilwat_fphlcc/audio/183Sounds20060713173801859seal_lil.mp3 net::ERR_UNKNOWN_URL_SCHEME`

Thank you!

**Comment by roedoejet** [comment]
I assumed this has something to do with the whitelist plugin, but I followed the instruction:

- I added `<meta http-equiv="Content-Security-Policy" content="* * 'self' default-src 'unsafe-inline' 'unsafe-eval' http://* https://* data: cdvfile://* content://*;">` to my index.html
- I removed whitelist and added this version https://github.com/agamemnus/cordova-plugin-whitelist
- this is my config.xml:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="com.firstvoices.lilwat_fphlcc" version="1.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>Lilwa_</name>
  <description>&#xD;
        An Ucwalmicwts/English Dictionary&#xD;
    </description>
  <author email="" href="">&#xD;
      Aidan Pine&#xD;
    </author>
  <content src="index.html"/>
    <allow-navigation href="*://*/*"/>
    <allow-intent href="*" />
    <access origin="*" />
    <access origin="content:///*" />
    <access origin="cdvfile:///*" />
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="SplashScreen" value="screen"/>
  <preference name="SplashScreenDelay" value="3000"/>
  <preference name="xwalkVersion" value="22+"/>
  <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect"/>
  <preference name="xwalkMode" value="embedded"/>
  <preference name="xwalkMultipleApk" value="true"/>
  <feature name="StatusBar">
    <param name="ios-package" onload="true" value="CDVStatusBar"/>
  </feature>
  <platform name="android">
    <icon src="resources\android\icon\drawable-ldpi-icon.png" density="ldpi"/>
    <icon src="resources\android\icon\drawable-mdpi-icon.png" density="mdpi"/>
    <icon src="resources\android\icon\drawable-hdpi-icon.png" density="hdpi"/>
    <icon src="resources\android\icon\drawable-xhdpi-icon.png" density="xhdpi"/>
    <icon src="resources\android\icon\drawable-xxhdpi-icon.png" density="xxhdpi"/>
    <icon src="resources\android\icon\drawable-xxxhdpi-icon.png" density="xxxhdpi"/>
    <splash src="resources\android\splash\drawable-land-ldpi-screen.png" density="land-ldpi"/>
    <splash src="resources\android\splash\drawable-land-mdpi-screen.png" density="land-mdpi"/>
    <splash src="resources\android\splash\drawable-land-hdpi-screen.png" density="land-hdpi"/>
    <splash src="resources\android\splash\drawable-land-xhdpi-screen.png" density="land-xhdpi"/>
    <splash src="resources\android\splash\drawable-land-xxhdpi-screen.png" density="land-xxhdpi"/>
    <splash src="resources\android\splash\drawable-land-xxxhdpi-screen.png" density="land-xxxhdpi"/>
    <splash src="resources\android\splash\drawable-port-ldpi-screen.png" density="port-ldpi"/>
    <splash src="resources\android\splash\drawable-port-mdpi-screen.png" density="port-mdpi"/>
    <splash src="resources\android\splash\drawable-port-hdpi-screen.png" density="port-hdpi"/>
    <splash src="resources\android\splash\drawable-port-xhdpi-screen.png" density="port-xhdpi"/>
    <splash src="resources\android\splash\drawable-port-xxhdpi-screen.png" density="port-xxhdpi"/>
    <splash src="resources\android\splash\drawable-port-xxxhdpi-screen.png" density="port-xxxhdpi"/>
  </platform>
  <platform name="ios">
    <icon src="resources\ios\icon\icon.png" width="57" height="57"/>
    <icon src="resources\ios\icon\icon@2x.png" width="114" height="114"/>
    <icon src="resources\ios\icon\icon-40.png" width="40" height="40"/>
    <icon src="resources\ios\icon\icon-40@2x.png" width="80" height="80"/>
    <icon src="resources\ios\icon\icon-40@3x.png" width="120" height="120"/>
    <icon src="resources\ios\icon\icon-50.png" width="50" height="50"/>
    <icon src="resources\ios\icon\icon-50@2x.png" width="100" height="100"/>
    <icon src="resources\ios\icon\icon-60.png" width="60" height="60"/>
    <icon src="resources\ios\icon\icon-60@2x.png" width="120" height="120"/>
    <icon src="resources\ios\icon\icon-60@3x.png" width="180" height="180"/>
    <icon src="resources\ios\icon\icon-72.png" width="72" height="72"/>
    <icon src="resources\ios\icon\icon-72@2x.png" width="144" height="144"/>
    <icon src="resources\ios\icon\icon-76.png" width="76" height="76"/>
    <icon src="resources\ios\icon\icon-76@2x.png" width="152" height="152"/>
    <icon src="resources\ios\icon\icon-83.5@2x.png" width="167" height="167"/>
    <icon src="resources\ios\icon\icon-small.png" width="29" height="29"/>
    <icon src="resources\ios\icon\icon-small@2x.png" width="58" height="58"/>
    <icon src="resources\ios\icon\icon-small@3x.png" width="87" height="87"/>
    <splash src="resources\ios\splash\Default-568h@2x~iphone.png" width="640" height="1136"/>
    <splash src="resources\ios\splash\Default-667h.png" width="750" height="1334"/>
    <splash src="resources\ios\splash\Default-736h.png" width="1242" height="2208"/>
    <splash src="resources\ios\splash\Default-Landscape-736h.png" width="2208" height="1242"/>
    <splash src="resources\ios\splash\Default-Landscape@2x~ipad.png" width="2048" height="1536"/>
    <splash src="resources\ios\splash\Default-Landscape@~ipadpro.png" width="2732" height="2048"/>
    <splash src="resources\ios\splash\Default-Landscape~ipad.png" width="1024" height="768"/>
    <splash src="resources\ios\splash\Default-Portrait@2x~ipad.png" width="1536" height="2048"/>
    <splash src="resources\ios\splash\Default-Portrait@~ipadpro.png" width="2048" height="2732"/>
    <splash src="resources\ios\splash\Default-Portrait~ipad.png" width="768" height="1024"/>
    <splash src="resources\ios\splash\Default@2x~iphone.png" width="640" height="960"/>
    <splash src="resources\ios\splash\Default~iphone.png" width="320" height="480"/>
  </platform>
  <icon src="resources\android\icon\drawable-xhdpi-icon.png"/>
</widget>
```

**Comment by agamemnus** [comment]
Do you have the Cordova Media plugin installed?

**Comment by roedoejet** [comment]
No I don't, am currently calling my audio with HTMLAudioElement:

```
srcURL = "content://com.firstvoices.lilwat_fphlcc/audio/" + src
var audio = new Audio(srcURL);
audio.play()
```

**Comment by agamemnus** [comment]
Try removing the whitelist plugin entirely and modifying the java file to ignore it.. let me find the code..

**Comment by agamemnus** [comment]
(Might be a few minutes, kind of getting pulled in all directions right now)

**Comment by agamemnus** [comment]
Also, try seeing if you can get any other format to work to rule out other issues... PNGs? Text files?

**Comment by roedoejet** [comment]
Tried with 'jpg' and same error:

`content://com.firstvoices.lilwat_fphlcc/audio/test.jpg Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME`

**Comment by agamemnus** [comment]
Maybe the underscore is doing it? I really don't know. Try text files also.

**Comment by roedoejet** [comment]
Same error with .txt ...

**Comment by agamemnus** [comment]
Try removing the underscore...

**Comment by roedoejet** [comment]
Unfortunately the same thing: `content://com.firstvoices.lilwatfphlcc/audio/test.jpg Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME`

**Comment by agamemnus** [comment]
Change out this file:

https://github.com/agamemnus/cordova-plugin-whitelist/blob/master/src/android/WhitelistPlugin.java

See what happens if you have `shouldAllowNavigation`, `shouldAllowRequest`, and `shouldOpenExternalUrl` to simply return `true`.

**Comment by roedoejet** [comment]
Same error.

**Comment by agamemnus** [comment]
And text files don't work either?

**Comment by roedoejet** [comment]
Nope. 

`content://com.firstvoices.lilwatfphlcc/audio/test.txt:1 GET content://com.firstvoices.lilwatfphlcc/audio/test.txt net::ERR_UNKNOWN_URL_SCHEME`

I just saw in a folder called "test-project-instructions-and-test-obb" in the plugin there's a step that's not included on the repo markdown. It says to add: `android.library.reference.2=../../plugins/com.flyingsoftgames.xapkreader/android-sdk/extras/google/play_apk_expansion/downloader_library`

to /platforms/android/project.properties

But I already have a value for that (see below), should I change it or is the above for testing with Google Play or another version?

```
target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.google.android.gms:play-services-base:+
android.library.reference.2=com.flyingsoftgames.xapkreader/lilwatfphlcc-downloader_library
android.library.reference.3=com.flyingsoftgames.xapkreader/lilwatfphlcc-library
cordova.gradle.include.1=cordova-plugin-crosswalk-webview/lilwatfphlcc-xwalk.gradle
```

**Comment by agamemnus** [comment]
This is for an older version. That should be removed.

Is your obb uncompressed?

**Comment by roedoejet** [comment]
Yes, I used 7zip and set the compression level to "store"

**Comment by agamemnus** [comment]
There must be something simple we are missing. Can you create a small sample project based on your settings that I can run?

**Comment by roedoejet** [comment]
Sure. You can clone the sandbox I have for the app here: https://github.com/roedoejet/lilwat-test.git

I'm calling the audio in controllers.js and have the img and text in www/templates/search.html

Or do you want something with fewer bells and whistles? This way you have what I have.

**Comment by roedoejet** [comment]
I've got to run out for a couple hours soon to another job but I'll be back in a few hours. I really appreciate you looking at this!

**Comment by agamemnus** [comment]
I assume you are testing this with Android... are you using the latest Android platform version, or which version? Your code doesn't say.

**Comment by roedoejet** [comment]
testing on a device running 5.1

**Comment by agamemnus** [comment]
Also -- the obb file -- it's not there.

**Comment by roedoejet** [comment]
Oops. Sorry about that. just added it but with most of the audio taken out. There are three files, audio/183Sounds20060420153235640knife_lil.mp3, audio/test.jpg, audio/test.txt

**Comment by agamemnus** [comment]
Thx.

**Comment by agamemnus** [comment]
Downloaded it and installed latest Android platform, but didn't test.... please remind me tomorrow...

**Comment by roedoejet** [comment]
Ok great. thanks, I'll do that.

**Comment by roedoejet** [comment]
Any update on this? ... a friendly reminder :)

**Comment by agamemnus** [comment]
Checking now.

**Comment by agamemnus** [comment]
Maven? Might this be an issue?

**Comment by agamemnus** [comment]
No, that isn't it. Still checking a few different things.

**Comment by agamemnus** [comment]
Here is the problem: you do not have the File plugin installed, and for some reason your whitelist plugin is some random old dev version.

**Comment by roedoejet** [comment]
Huh, I didn't know I needed the File plugin, but that makes sense. The whitelist plugin I added was the one here which is listed on the readme, is that not right? https://github.com/agamemnus/cordova-plugin-whitelist

**Comment by agamemnus** [comment]
Oh, weird. I had no idea it was a dev version... but it IS old. :P

**Comment by roedoejet** [comment]
lol yes, so is it still required or does the newer version/main repo of cordova-plugin-whitelist work?

**Comment by agamemnus** [comment]
I did do a few different things.

If that still doesn't work, try instalilng a clean whitelist plugin as well, and try this for a meta tag:
``<meta http-equiv="Content-Security-Policy" content="default-src * 'self' 'unsafe-inline' http://* https://* 'unsafe-eval';">``

**Comment by agamemnus** [comment]
No, it's not required if you have the various tags to change the security policy, etc.

**Comment by agamemnus** [comment]
You could also just delete the plugin...

**Comment by roedoejet** [comment]
Ok, I got the net::ERR_UNKNOWN_URL_SCHEME error to go away by removing the whitelist plugin altogether and by using the updated meta tag above. Now I'm getting 404's :( did the content actually come through for you? Thanks so much again for looking into this. I'll keep looking into it.

**Comment by agamemnus** [comment]
It did. You added the File plugin?

**Comment by agamemnus** [comment]
Update your code on github and I'll look at it again. I did do a number of
things which might have had an effect...

**Comment by roedoejet** [comment]
Yep. I added the File plugin. It looks like the cordova-compat plugin got installed as a dependency or something. I've updated the repo with my changes

**Comment by agamemnus** [comment]
Ok, give me a bit and I will try again.

**Comment by roedoejet** [comment]
thanks!

**Comment by agamemnus** [comment]
It'll be tomorrow. I'm stuck on a bug  (?) in another library and very tired. Sry.

**Comment by roedoejet** [comment]
no problem. you could also make a pull request to the repo with your local copy and I can try and see what other changes you made. g'night!

**Comment by roedoejet** [comment]
any luck? I'm heading out to work but will be back this afternoon/evening to have another look. Had me stumped yesterday.

**Comment by agamemnus** [comment]
I was busy all day yesterday. I am looking now, that I am wrapping up my bug work for the other project.

**Comment by roedoejet** [comment]
OK, no problem. Again, I really appreciate you looking into this. Be back in a few hours.

**Comment by agamemnus** [comment]
It's not working. I keep having issues with `Error: Unexpected end of JSON input` when I try to add the android platform, etc.

**Comment by roedoejet** [comment]
Looks like for some reason my fetch.json was invalid json. I just pushed a version that is working. Sorry about that.

**Comment by roedoejet** [comment]
Yeah. So same thing with the version that's on that repo; I get 404s without Cordova Whitelist, and unknown url scheme errors with Cordova Whitelist.

**Comment by agamemnus** [comment]
Checking in a few minutes...

**Comment by agamemnus** [comment]
Fell asleep.

**Comment by agamemnus** [comment]
Unfortunately, something got borked yesterday. I don't know what happened. Any ideas?

````
C:\test>cordova run android
ANDROID_HOME=C:\Android\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_20
Error: Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle
in your path, or install Android Studio
````

**Comment by agamemnus** [comment]
I ended up manually installing Gradle 3.5. I don't think that is right...

**Comment by agamemnus** [comment]
I noticed that putting the obb in the external card does not work. That is a problem... this used to work. Probably one of the newer updates to the plugin broke the pathing. Can you check if this fixes the issue, before doing anything else?

If you are using an external card already and it works, try:
`cordova platform add android`
It installed 6.2.3.
`cordova run android`
Compiled the app. Took a while. Lots of x86 stuff. Not sure why. It worked.

**Comment by roedoejet** [comment]
might be an issue with the version of Android Studio https://github.com/driftyco/ionic/issues/10604

**Comment by roedoejet** [comment]
I tried putting the obb on both my SD and phone storage, same thing. With whitelist, unknown url schemes, and without whitelist I get 404s

**Comment by agamemnus** [comment]
I am not using Android Studio. Or Ionic, for that matter...

**Comment by roedoejet** [comment]
Hm. ok, that might be part of the 

`Error: Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle
in your path, or install Android Studio`

You say you got it working though?

**Comment by agamemnus** [comment]
Yes. Installed Gradle 3.5 by itself.

**Comment by roedoejet** [comment]
and you didn't get any of the errors I'm getting with your build?

**Comment by agamemnus** [comment]
As of today, I only got errors like that when the file was missing in the internal memory drive.

**Comment by agamemnus** [comment]
I also added back the whitelist plugin. I think.

**Comment by roedoejet** [comment]
because you said you were getting a lot of x86 stuff, I removed:

`cdvBuildMultipleApks=false` from build-extras.gradle

and now I'm getting this error:

`Not allowed to load local resource: content://com.firstvoices.lilwatfphlcc/audio/test.txt`

and unknown url scheme errors on both the jpg and txt as well

**Comment by roedoejet** [comment]
can you PR your local copy? I can look at that.

**Comment by agamemnus** [comment]
Seems like a lot of work to upload it. Try creating an Android build and
let me try from there. Are you trying with "cordova run android"?

**Comment by roedoejet** [comment]
You want me to upload an android build? I've been using ionic run android but just tried with cordova run android and the same issue came up.

**Comment by roedoejet** [comment]
just apk or add my whole platform/android folder to the repo?

**Comment by agamemnus** [comment]
Actually. Let's try the apk. That's easier.

**Comment by roedoejet** [comment]
K I can build a few, with whitelist and without etc.. would that be helpful?

**Comment by agamemnus** [comment]
Idk. Ok.

**Comment by agamemnus** [comment]
Lmk when ready.

**Comment by roedoejet** [comment]
made 3 different builds, uploading to repo's root directory in folder called "builds". I'll post when finished uploading.

**Comment by roedoejet** [comment]
forgot about githubs 50mb limit. Here's a link you can use https://drive.google.com/open?id=0BwW7wFq3J1ieaHBXNC16bGhUV0k

**Comment by agamemnus** [comment]
The first one works.

Where are you putting your obb file? `Phone/Android/obb/com.firstvoices.lilwatfphlcc/`?

**Comment by roedoejet** [comment]
yep `Phone/Android/obb/com.firstvoices.lilwatfphlcc/main.1.com.firstvoices.lilwatfphlcc.obb`

**Comment by agamemnus** [comment]
Android version?

**Comment by agamemnus** [comment]
Do you get a permissions request when you first install the apk?

**Comment by roedoejet** [comment]
Android 5.1 running on a device. Yes I get the list of device access permissions in the package installer before clicking 'install'. Nothing explicitly asking for permission.

**Comment by agamemnus** [comment]
Can you send me a screenshot? It might be a version issue. I guess one of the last few updates broke it. :| I have 6.0.1.

**Comment by roedoejet** [comment]
![image](https://cloud.githubusercontent.com/assets/14815080/25784336/bb1a3b18-331f-11e7-9cea-6d699676e0e1.png)

**Comment by roedoejet** [comment]
that sufficient?

**Comment by agamemnus** [comment]
I wanted to see your screenshot of the permissions screen. I think we are talking about different things.

**Comment by roedoejet** [comment]
do you mean this?
![screenshot_2017-05-07-13-10-46](https://cloud.githubusercontent.com/assets/14815080/25784722/dab35868-3326-11e7-9760-107f645bb71a.png)
![screenshot_2017-05-07-13-10-41](https://cloud.githubusercontent.com/assets/14815080/25784727/e2050896-3326-11e7-88fd-de2eccc0cc51.png)

**Comment by agamemnus** [comment]
Definitely not the same permission screen. Let me show you mine.

**Comment by agamemnus** [comment]
Not sure that attached email worked. Anyway, yeah. I think it is down to the last few updates I made to the code over the last month (PRs from others). Try seeing if you can test it in 6+?

**Comment by roedoejet** [comment]
your attached email didn't come through. I don't have any devices with 6+, working on emulating right now, will post results.

**Comment by roedoejet** [comment]
I a proper permissions modal on it this time. But am still trying to get the .obb to the right place in Genymotion. Without the obb there, I'm still getting the unknown url scheme error

![screenshot-2017-05-07_15 23 55 607](https://cloud.githubusercontent.com/assets/14815080/25785579/3b729fa8-3339-11e7-8348-1e19a2940382.png)

**Comment by agamemnus** [comment]
I encountered the same problem with Genymotion a while ago. I didn't know if it was fixable.

Maybe you can just try the version from like 2 months ago.

**Comment by roedoejet** [comment]
Isn't that permission modal only supposed to come up in Android 6 anyways?  seems to say that here anyways: https://github.com/agamemnus/cordova-plugin-xapkreader/commit/a2cc601fd58867e52e056321dc0bca2bd964e769

**Comment by agamemnus** [comment]
Yeah. But, uh, that's not the "reason" it might not be working... long story. Just try an older version from the history..... (sorry, it is a mess!)

**Comment by roedoejet** [comment]
is there a specific commit you can recommend?

**Comment by agamemnus** [comment]
Try https://github.com/agamemnus/cordova-plugin-xapkreader/tree/3ec6ec902e35c01343cfc1cf0b79b936e5c09ead.

**Comment by roedoejet** [comment]
Ok, rebuilt with 3ec6ec902e35c01343cfc1cf0b79b936e5c09ead and same thing. 404s without whitelist, unknown url scheme without whitelist :(

**Comment by agamemnus** [comment]
Well, it is clearly an issue with the Android version or some configuration you have... of course the issue ultimately originates in the code, but it will be difficult to debug. Maybe console logging the actual path that the code calculates (with Java) can yield clues.

**Comment by marcelo-sc** [comment]
Could you solve this problem @roedoejet

**Comment by roedoejet** [comment]
@marcelo-sc unfortunately I couldn't. Admittedly, I only worked on it for about another half day before giving up. I made some compromises to the app though and could basically do what I wanted to do with cordova-plugin-file and cordova-plugin-file-transfer so I haven't had to try getting this to work again.

**Comment by agamemnus** [comment]
@marcelo-sc: What Android version were you on when you had this issue?

**Comment by marcelo-sc** [comment]
@roedoejet what did you end up doing ?

@agamemnus I tested in a device with android 6.0

**Comment by roedoejet** [comment]
@marcelo-sc I wanted audio for a dictionary to be available offline. I ended up hosting the audio on a server and then letting the user either download all of the audio at once or downloading and caching the files "on demand" individually from the server using cordova plugins File & File Transfer. I only had to do this for Android though. So the results looks something like:


```
if (ionic.Platform.isAndroid()) {
                if (src != undefined) {
                    srcURL = "http://www.***" + src
                    srcFN = src.replace(/\//g, '')
                    $cordovaFile.checkFile(cordova.file.dataDirectory, srcFN)
                        .then(function (success) {
                            var audio = new Audio(cordova.file.dataDirectory + srcFN)
                            audio.play()
                        }, function (error) {
                            var url = srcURL;
                            var targetPath = cordova.file.dataDirectory + srcFN;
                            var trustHosts = true;
                            var options = {};

                            $cordovaFileTransfer.download(url, targetPath, options, trustHosts)
                                .then(function (result) {
                                    var audio = new Audio(targetPath);
                                    audio.play()
                                }, function (err) {
                                    $scope.showExpAlert()
                                }, function (progress) {
                                    $timeout(function () {
                                        $scope.downloadProgress = (progress.loaded / progress.total) * 100;
                                    });
                                });
                        }, false);
                } else {
                    $scope.showExpAlert()
                }
           }
     };

```

Obviously there is some code here specific to my app, but just to give you an idea...

**Comment by marcelo-sc** [comment]
@roedoejet Thanks
I am very close to do the same

**Comment by agamemnus** [comment]
Should definitely work with 6... not sure what you guys are doing!

**Comment by marcelo-sc** [comment]
I don't know either :) @agamemnus
